import type { ISharkcraftInspection } from '@shrkcrft/inspector';
import { aggregateActionHints, KnowledgeType, type IKnowledgeEntry } from '@shrkcrft/knowledge';
import { priorityWeight } from '@shrkcrft/knowledge';

export type ExportFormat =
  | 'agents-md'
  | 'claude-md'
  | 'cursor-rules'
  | 'copilot-instructions';

export interface ExportOptions {
  format: ExportFormat;
  /** Optional task to scope the export. */
  task?: string;
  /** Max number of rules to include. Default 12. */
  maxRules?: number;
  /** Max number of path conventions to include. Default 10. */
  maxPaths?: number;
}

export interface ExportResult {
  format: ExportFormat;
  /** Suggested relative output path within the project. */
  suggestedPath: string;
  /** Rendered content. */
  content: string;
}

const DEFAULT_OUTPUT_PATH: Record<ExportFormat, string> = {
  'agents-md': 'AGENTS.md',
  'claude-md': 'CLAUDE.md',
  'cursor-rules': '.cursor/rules/sharkcraft.mdc',
  'copilot-instructions': '.github/copilot-instructions.md',
};

function selectTopByPriority<T extends IKnowledgeEntry>(entries: readonly T[], limit: number): T[] {
  return [...entries]
    .sort((a, b) => priorityWeight(b.priority as never) - priorityWeight(a.priority as never))
    .slice(0, limit);
}

function shortBullet(text: string, maxLen: number = 160): string {
  const single = text.replace(/\s+/g, ' ').trim();
  if (single.length <= maxLen) return single;
  return single.slice(0, maxLen - 1) + '…';
}

function gatherRulesAndPaths(
  inspection: ISharkcraftInspection,
  options: ExportOptions,
): { rules: IKnowledgeEntry[]; paths: IKnowledgeEntry[] } {
  const allRules = inspection.knowledgeEntries.filter(
    (e) => String(e.type) === KnowledgeType.Rule,
  );
  const allPaths = inspection.knowledgeEntries.filter(
    (e) => String(e.type) === KnowledgeType.Path,
  );
  const rules = selectTopByPriority(allRules, options.maxRules ?? 12);
  const paths = selectTopByPriority(allPaths, options.maxPaths ?? 10);
  return { rules, paths };
}

function renderRulesSection(rules: readonly IKnowledgeEntry[]): string {
  if (rules.length === 0) return '';
  const lines: string[] = [];
  for (const r of rules) {
    lines.push(`- **${r.title}** (\`${r.id}\`, ${r.priority}) — ${shortBullet(r.summary ?? r.content)}`);
  }
  return lines.join('\n');
}

function renderPathsSection(paths: readonly IKnowledgeEntry[]): string {
  if (paths.length === 0) return '';
  const lines: string[] = [];
  for (const p of paths) {
    const path = (p.metadata?.path as string | undefined) ?? '';
    lines.push(`- \`${p.id}\` → \`${path}\` — ${shortBullet((p.metadata?.description as string) ?? p.title)}`);
  }
  return lines.join('\n');
}

function renderAgentActions(inspection: ISharkcraftInspection): string {
  const agg = aggregateActionHints(inspection.knowledgeEntries);
  const lines: string[] = [];
  if (agg.commands.length) {
    lines.push('Run these commands when relevant:');
    for (const c of agg.commands.slice(0, 8)) {
      const purpose = c.purpose ? ` — ${c.purpose}` : '';
      lines.push(`- \`${c.command}\`${purpose}`);
    }
    lines.push('');
  }
  if (agg.mcpTools.length) {
    lines.push('Prefer these MCP tools (when an MCP server is connected):');
    for (const t of agg.mcpTools.slice(0, 8)) {
      lines.push(`- \`${t.tool}\``);
    }
    lines.push('');
  }
  if (agg.forbiddenActions.length) {
    lines.push('Do not:');
    for (const f of agg.forbiddenActions.slice(0, 8)) lines.push(`- ${f}`);
    lines.push('');
  }
  if (agg.verificationCommands.length) {
    lines.push('Verify your work with:');
    for (const c of agg.verificationCommands.slice(0, 6)) lines.push(`- \`${c}\``);
    lines.push('');
  }
  return lines.join('\n').trim();
}

const PREAMBLE = `> Generated by \`shrk export\`. SharkCraft (structured knowledge + MCP) is the source of truth; this file is a compatibility shim for clients that read flat markdown.`;

function renderBody(inspection: ISharkcraftInspection, options: ExportOptions): string {
  const { rules, paths } = gatherRulesAndPaths(inspection, options);
  const sections: string[] = [];

  if (inspection.config?.projectName) {
    sections.push(`## Project\n\n${inspection.config.projectName}${inspection.config.description ? ` — ${inspection.config.description}` : ''}`);
  }

  if (options.task) {
    sections.push(`## Task focus\n\n_${options.task}_`);
  }

  const rulesBody = renderRulesSection(rules);
  if (rulesBody) sections.push(`## Rules to follow\n\n${rulesBody}`);

  const pathsBody = renderPathsSection(paths);
  if (pathsBody) sections.push(`## Where files belong\n\n${pathsBody}`);

  const actions = renderAgentActions(inspection);
  if (actions) sections.push(`## Agent actions\n\n${actions}`);

  if (inspection.pipelines.length) {
    const pipelines = inspection.pipelines.slice(0, 5).map((p) => `- \`${p.id}\` — ${p.description}`);
    sections.push(`## Pipelines (declarative workflows)\n\n${pipelines.join('\n')}\n\nRun \`shrk pipelines get <id>\` for full step lists.`);
  }

  return sections.join('\n\n');
}

export function renderExport(
  inspection: ISharkcraftInspection,
  options: ExportOptions,
): ExportResult {
  const body = renderBody(inspection, options);
  const suggestedPath = DEFAULT_OUTPUT_PATH[options.format];

  let content = '';
  switch (options.format) {
    case 'agents-md':
      content = `# Agents Guide\n\n${PREAMBLE}\n\n${body}\n`;
      break;
    case 'claude-md':
      content = `# CLAUDE.md\n\n${PREAMBLE}\n\nThis file is read by Claude Code (claude.ai/code) at session start. Treat it as a compatibility view of the project's SharkCraft knowledge — use the MCP server (\`shrk mcp serve\`) for the live, queryable source of truth.\n\n${body}\n`;
      break;
    case 'cursor-rules':
      // Cursor MDC frontmatter: leave alwaysApply off so the user can tune.
      content = `---\ndescription: SharkCraft project rules (auto-generated)\nalwaysApply: false\n---\n\n${PREAMBLE}\n\n${body}\n`;
      break;
    case 'copilot-instructions':
      content = `# Copilot instructions\n\n${PREAMBLE}\n\n${body}\n`;
      break;
  }

  return { format: options.format, suggestedPath, content };
}

export function isExportFormat(value: string): value is ExportFormat {
  return (
    value === 'agents-md' ||
    value === 'claude-md' ||
    value === 'cursor-rules' ||
    value === 'copilot-instructions'
  );
}

export const ALL_EXPORT_FORMATS: readonly ExportFormat[] = Object.freeze([
  'agents-md',
  'claude-md',
  'cursor-rules',
  'copilot-instructions',
]);
