import type { ISharkcraftInspection } from '@shrkcrft/inspector';
import { aggregateActionHints, KnowledgeType, type IKnowledgeEntry } from '@shrkcrft/knowledge';
import { priorityWeight } from '@shrkcrft/knowledge';

export type ExportFormat =
  | 'agents-md'
  | 'claude-md'
  | 'claude-skill'
  | 'cursor-rules'
  | 'copilot-instructions';

export interface ExportOptions {
  format: ExportFormat;
  /** Optional task to scope the export. */
  task?: string;
  /** Max number of rules to include. Default 12. */
  maxRules?: number;
  /** Max number of path conventions to include. Default 10. */
  maxPaths?: number;
}

export interface ExportResult {
  format: ExportFormat;
  /** Suggested relative output path within the project. */
  suggestedPath: string;
  /** Rendered content. */
  content: string;
}

function projectSlug(name: string | undefined): string {
  if (!name) return 'project';
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48) || 'project'
  );
}

function defaultOutputFor(format: ExportFormat, inspection: ISharkcraftInspection): string {
  switch (format) {
    case 'agents-md':
      return 'AGENTS.md';
    case 'claude-md':
      return 'CLAUDE.md';
    case 'claude-skill':
      return `.claude/skills/${projectSlug(inspection.config?.projectName)}/SKILL.md`;
    case 'cursor-rules':
      return '.cursor/rules/sharkcraft.mdc';
    case 'copilot-instructions':
      return '.github/copilot-instructions.md';
  }
}

function selectTopByPriority<T extends IKnowledgeEntry>(entries: readonly T[], limit: number): T[] {
  return [...entries]
    .sort((a, b) => priorityWeight(b.priority as never) - priorityWeight(a.priority as never))
    .slice(0, limit);
}

function shortBullet(text: string, maxLen: number = 160): string {
  const single = text.replace(/\s+/g, ' ').trim();
  if (single.length <= maxLen) return single;
  return single.slice(0, maxLen - 1) + '…';
}

function gatherRulesAndPaths(
  inspection: ISharkcraftInspection,
  options: ExportOptions,
): { rules: IKnowledgeEntry[]; paths: IKnowledgeEntry[] } {
  const allRules = inspection.knowledgeEntries.filter(
    (e) => String(e.type) === KnowledgeType.Rule,
  );
  const allPaths = inspection.knowledgeEntries.filter(
    (e) => String(e.type) === KnowledgeType.Path,
  );
  const rules = selectTopByPriority(allRules, options.maxRules ?? 12);
  const paths = selectTopByPriority(allPaths, options.maxPaths ?? 10);
  return { rules, paths };
}

function renderRulesSection(rules: readonly IKnowledgeEntry[]): string {
  if (rules.length === 0) return '';
  const lines: string[] = [];
  for (const r of rules) {
    lines.push(`- **${r.title}** (\`${r.id}\`, ${r.priority}) — ${shortBullet(r.summary ?? r.content)}`);
  }
  return lines.join('\n');
}

function renderPathsSection(paths: readonly IKnowledgeEntry[]): string {
  if (paths.length === 0) return '';
  const lines: string[] = [];
  for (const p of paths) {
    const path = (p.metadata?.path as string | undefined) ?? '';
    lines.push(`- \`${p.id}\` → \`${path}\` — ${shortBullet((p.metadata?.description as string) ?? p.title)}`);
  }
  return lines.join('\n');
}

function renderAgentActions(inspection: ISharkcraftInspection): string {
  const agg = aggregateActionHints(inspection.knowledgeEntries);
  const lines: string[] = [];
  if (agg.commands.length) {
    lines.push('Run these commands when relevant:');
    for (const c of agg.commands.slice(0, 8)) {
      const purpose = c.purpose ? ` — ${c.purpose}` : '';
      lines.push(`- \`${c.command}\`${purpose}`);
    }
    lines.push('');
  }
  if (agg.mcpTools.length) {
    lines.push('Prefer these MCP tools (when an MCP server is connected):');
    for (const t of agg.mcpTools.slice(0, 8)) {
      lines.push(`- \`${t.tool}\``);
    }
    lines.push('');
  }
  if (agg.forbiddenActions.length) {
    lines.push('Do not:');
    for (const f of agg.forbiddenActions.slice(0, 8)) lines.push(`- ${f}`);
    lines.push('');
  }
  if (agg.verificationCommands.length) {
    lines.push('Verify your work with:');
    for (const c of agg.verificationCommands.slice(0, 6)) lines.push(`- \`${c}\``);
    lines.push('');
  }
  return lines.join('\n').trim();
}

const PREAMBLE = `> Generated by \`shrk export\`. SharkCraft (structured knowledge + MCP) is the source of truth; this file is a compatibility shim for clients that read flat markdown.`;

function renderBody(inspection: ISharkcraftInspection, options: ExportOptions): string {
  const { rules, paths } = gatherRulesAndPaths(inspection, options);
  const sections: string[] = [];

  if (inspection.config?.projectName) {
    sections.push(`## Project\n\n${inspection.config.projectName}${inspection.config.description ? ` — ${inspection.config.description}` : ''}`);
  }

  if (options.task) {
    sections.push(`## Task focus\n\n_${options.task}_`);
  }

  const rulesBody = renderRulesSection(rules);
  if (rulesBody) sections.push(`## Rules to follow\n\n${rulesBody}`);

  const pathsBody = renderPathsSection(paths);
  if (pathsBody) sections.push(`## Where files belong\n\n${pathsBody}`);

  const actions = renderAgentActions(inspection);
  if (actions) sections.push(`## Agent actions\n\n${actions}`);

  if (inspection.pipelines.length) {
    const pipelines = inspection.pipelines.slice(0, 5).map((p) => `- \`${p.id}\` — ${p.description}`);
    sections.push(`## Pipelines (declarative workflows)\n\n${pipelines.join('\n')}\n\nRun \`shrk pipelines get <id>\` for full step lists.`);
  }

  return sections.join('\n\n');
}

/**
 * Filter rules / paths to the high-signal subset for an inlined skill.
 *
 * Every rule the skill carries pays in Claude's context every time the
 * skill is loaded. Low-priority items dilute the signal of the
 * load-bearing ones (`Critical` safety + `High` architecture). We keep
 * only Critical + High by default, falling back to "all" only if the
 * filtered list is empty (e.g. a repo with no high-priority entries
 * yet shouldn't ship an empty skill).
 */
function filterHighSignal<T extends IKnowledgeEntry>(entries: readonly T[]): T[] {
  const filtered = entries.filter((e) => {
    const p = String(e.priority).toLowerCase();
    return p === 'critical' || p === 'high';
  });
  return filtered.length > 0 ? filtered : [...entries];
}

/**
 * Render the body in tight, decision-driving form for the Claude Code
 * Skill format. Skills get loaded into Claude's prompt when the skill's
 * `description` matches the current task, so the body must be short and
 * directly actionable — no preamble, no metadata about generation, no
 * pipelines (Claude can run `shrk task` for those when needed).
 *
 * Sections:
 *   1. Where files belong (path conventions, top N) — most-leveraged signal.
 *   2. Rules to follow (Critical + High only) — pads context otherwise.
 *   3. Do / Don't — forbidden actions and verification commands.
 *   4. How to write code in this repo — the gen → review → apply loop
 *      verbatim, since Claude needs to know shrk is the write path.
 */
function renderSkillBody(inspection: ISharkcraftInspection, options: ExportOptions): string {
  const { rules: allRules, paths: allPaths } = gatherRulesAndPaths(inspection, {
    ...options,
    // Pull more upfront, then filter down to high-signal — keeps the
    // softcap-at-15 default but the inlined skill stays terse.
    maxRules: options.maxRules ?? 24,
    maxPaths: options.maxPaths ?? 18,
  });
  // Skills are inlined into the prompt — every entry costs Claude
  // context. Only ship the items the user said are load-bearing.
  const rules = filterHighSignal(allRules).slice(0, options.maxRules ?? 12);
  const paths = filterHighSignal(allPaths).slice(0, options.maxPaths ?? 10);
  const sections: string[] = [];

  if (inspection.config?.description) {
    sections.push(`## About this codebase\n\n${inspection.config.description}`);
  }

  const pathsBody = renderPathsSection(paths);
  if (pathsBody) {
    sections.push(
      `## Where files belong\n\nWhen creating or moving a file, place it according to these conventions:\n\n${pathsBody}`,
    );
  }

  const rulesBody = renderRulesSection(rules);
  if (rulesBody) {
    sections.push(
      `## Rules this codebase follows\n\nApply these whenever you generate, modify, or review code:\n\n${rulesBody}`,
    );
  }

  const agg = aggregateActionHints(inspection.knowledgeEntries);
  const doDont: string[] = [];
  if (agg.forbiddenActions.length) {
    doDont.push('**Do not:**');
    for (const f of agg.forbiddenActions.slice(0, 8)) doDont.push(`- ${f}`);
    doDont.push('');
  }
  if (agg.verificationCommands.length) {
    doDont.push('**Verify changes with:**');
    for (const c of agg.verificationCommands.slice(0, 6)) doDont.push(`- \`${c}\``);
  }
  if (doDont.length) {
    sections.push(`## Do / Don't\n\n${doDont.join('\n').trim()}`);
  }

  sections.push(
    `## How to write code in this repo\n\n` +
      `This repository uses [SharkCraft](https://github.com/shrkcrft/sharkcraft) to gate writes — the CLI is the only write path, and writes go through a plan → review → apply loop.\n\n` +
      `1. **Get a task packet** before non-trivial work: \`shrk task "<one-sentence task>"\` returns the focused rules, paths, templates, and verification commands for that task.\n` +
      `2. **Scaffold via templates** instead of writing files freehand: \`shrk gen <template-id> <name> --dry-run --save-plan plan.json\` produces a signed plan.\n` +
      `3. **Apply the plan** through the CLI: \`shrk apply plan.json --verify-signature\` — never write through MCP.\n` +
      `4. **Check the result**: \`shrk check boundaries\` + the verification commands listed above.\n\n` +
      `For ad-hoc questions about the codebase, query the MCP server (\`shrk mcp serve\`) or run \`shrk context --task "<query>"\` for token-budgeted context.`,
  );

  return sections.join('\n\n');
}

/**
 * Build the YAML frontmatter for a Claude Code Skill. The `description`
 * field is what Claude uses to decide whether to load this skill — keep
 * it specific (project name + what's covered) so it doesn't trigger on
 * unrelated tasks.
 */
function renderSkillFrontmatter(inspection: ISharkcraftInspection): string {
  const slug = projectSlug(inspection.config?.projectName);
  const projectName = inspection.config?.projectName ?? slug;
  const description =
    `Codebase rules, path conventions, and review gates for ${projectName}. ` +
    `Use this skill whenever generating, modifying, or reviewing code in this repository — ` +
    `it tells you the per-file path conventions, the architecture boundaries, the verification commands, ` +
    `and the safe write path (CLI plan → review → apply).`;
  return `---\nname: ${slug}\ndescription: ${JSON.stringify(description)}\n---`;
}

export function renderExport(
  inspection: ISharkcraftInspection,
  options: ExportOptions,
): ExportResult {
  const suggestedPath = defaultOutputFor(options.format, inspection);

  let content = '';
  switch (options.format) {
    case 'agents-md': {
      const body = renderBody(inspection, options);
      content = `# Agents Guide\n\n${PREAMBLE}\n\n${body}\n`;
      break;
    }
    case 'claude-md': {
      const body = renderBody(inspection, options);
      content = `# CLAUDE.md\n\n${PREAMBLE}\n\nThis file is read by Claude Code (claude.ai/code) at session start. Treat it as a compatibility view of the project's SharkCraft knowledge — use the MCP server (\`shrk mcp serve\`) for the live, queryable source of truth.\n\n${body}\n`;
      break;
    }
    case 'claude-skill': {
      // Claude Code Skill: YAML frontmatter declares when to load this,
      // body is tight decision-driving content. No preamble, no boilerplate
      // — every token in here costs Claude context when loaded.
      const frontmatter = renderSkillFrontmatter(inspection);
      const projectName = inspection.config?.projectName ?? 'this codebase';
      const body = renderSkillBody(inspection, options);
      content = `${frontmatter}\n\n# ${projectName} — codebase guide\n\n${body}\n`;
      break;
    }
    case 'cursor-rules':
      // Cursor MDC frontmatter: leave alwaysApply off so the user can tune.
      content = `---\ndescription: SharkCraft project rules (auto-generated)\nalwaysApply: false\n---\n\n${PREAMBLE}\n\n${renderBody(inspection, options)}\n`;
      break;
    case 'copilot-instructions':
      content = `# Copilot instructions\n\n${PREAMBLE}\n\n${renderBody(inspection, options)}\n`;
      break;
  }

  return { format: options.format, suggestedPath, content };
}

export function isExportFormat(value: string): value is ExportFormat {
  return (
    value === 'agents-md' ||
    value === 'claude-md' ||
    value === 'claude-skill' ||
    value === 'cursor-rules' ||
    value === 'copilot-instructions'
  );
}

export const ALL_EXPORT_FORMATS: readonly ExportFormat[] = Object.freeze([
  'agents-md',
  'claude-md',
  'claude-skill',
  'cursor-rules',
  'copilot-instructions',
]);
