import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import * as nodePath from 'node:path';
import {
  buildReviewPacket,
  buildReviewPacketV2,
  buildReviewPacketV3,
  inspectSharkcraft,
  renderReviewComment,
  renderReviewCommentV2,
  renderReviewCommentV3,
  REVIEW_PACKET_V2_SCHEMA,
  REVIEW_PACKET_V3_SCHEMA,
  type IReviewPacket,
  type IReviewPacketV2,
  type IReviewPacketV3,
} from '@shrkcrft/inspector';
import {
  flagBool,
  flagNumber,
  flagString,
  flagList,
  resolveCwd,
  type ICommandHandler,
  type ParsedArgs,
} from '../command-registry.ts';
import { asJson, header, kv } from '../output/format-output.ts';

interface IScaffoldGithubActionOptions {
  withBoundaries: boolean;
  withCoverage: boolean;
  withDrift: boolean;
  artifactOnly: boolean;
  commentPlaceholder: boolean;
}

function renderGithubActionYaml(options: IScaffoldGithubActionOptions): string {
  const steps: string[] = [];
  const artifacts: { name: string; path: string }[] = [
    { name: 'sharkcraft-review-packet', path: 'review-packet.json' },
  ];
  steps.push(
    '      - name: Build review packet',
    '        run: bun run shrk review --since origin/main --json > review-packet.json',
  );
  if (options.withBoundaries) {
    steps.push(
      '      - name: Check boundaries',
      '        run: bun run shrk check boundaries --json > boundaries.json',
    );
    artifacts.push({ name: 'sharkcraft-boundaries', path: 'boundaries.json' });
  }
  if (options.withCoverage) {
    steps.push(
      '      - name: Coverage report',
      '        run: bun run shrk coverage --json > coverage.json',
    );
    artifacts.push({ name: 'sharkcraft-coverage', path: 'coverage.json' });
  }
  if (options.withDrift) {
    steps.push(
      '      - name: Drift report',
      '        run: bun run shrk drift --json > drift.json',
    );
    artifacts.push({ name: 'sharkcraft-drift', path: 'drift.json' });
  }
  for (const a of artifacts) {
    steps.push(
      '      - uses: actions/upload-artifact@v4',
      '        with:',
      `          name: ${a.name}`,
      `          path: ${a.path}`,
    );
  }
  if (options.commentPlaceholder && !options.artifactOnly) {
    steps.push(
      '      - name: Render PR comment markdown',
      '        run: bun run shrk review render-comment review-packet.json --output review-comment.md',
      '      - name: PR comment placeholder',
      '        run: |',
      '          echo "Generated review-comment.md from review-packet.json."',
      '          echo "Post it via \\`gh pr comment --body-file review-comment.md\\` or actions/github-script."',
    );
  }
  const commentNoteIncluded =
    options.commentPlaceholder && !options.artifactOnly;
  const lines: string[] = [
    '# .github/workflows/sharkcraft-review.yml',
    '# Generated by `shrk review scaffold github-action`.',
    '#',
    '# On every pull request:',
    '#   1. Check out the PR (with origin/main available so `shrk review --since` can diff).',
    '#   2. Install Bun and workspace deps.',
    '#   3. Run the selected SharkCraft checks and upload their JSON artifacts.',
    '#',
    commentNoteIncluded
      ? '# A comment-placeholder step is included so you can wire `actions/github-script`'
      : '# Posting artifacts as a PR comment is left as a follow-up — wire it via',
    commentNoteIncluded
      ? '# or `gh pr comment` later. The artifacts above contain the full payload.'
      : '# `actions/github-script` or `gh pr comment` once you have a stable schema.',
    'name: SharkCraft review packet',
    '',
    'on:',
    '  pull_request:',
    '    branches: [main]',
    '',
    'jobs:',
    '  review:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '        with:',
    '          fetch-depth: 0',
    "      - uses: oven-sh/setup-bun@v1",
    '        with:',
    "          bun-version: '1.1'",
    '      - run: bun install',
    ...steps,
    '',
  ];
  return lines.join('\n');
}

function scaffoldOptionsFromArgs(args: ParsedArgs): IScaffoldGithubActionOptions {
  return {
    withBoundaries: flagBool(args, 'with-boundaries'),
    withCoverage: flagBool(args, 'with-coverage'),
    withDrift: flagBool(args, 'with-drift'),
    artifactOnly: flagBool(args, 'artifact-only'),
    commentPlaceholder: flagBool(args, 'comment-placeholder'),
  };
}

export const reviewCommand: ICommandHandler = {
  name: 'review',
  description:
    'Build a PR-review packet: changed files (via git), affected path conventions, relevant rules/templates/pipelines, boundary violations on those files, missing-test heuristic, verification commands. Also: `shrk review scaffold github-action` prints a workflow template with optional `--with-boundaries / --with-coverage / --with-drift / --artifact-only / --comment-placeholder` flags. `shrk review render-comment <packet.json>` renders a Markdown PR comment from a saved packet.',
  usage:
    'shrk [--cwd <dir>] review [--since <ref>] [--staged] [--files a,b] [--json] | shrk review scaffold github-action [...] | shrk review render-comment <packet.json> [--output <file>]',
  async run(args: ParsedArgs): Promise<number> {
    if (args.positional[0] === 'scaffold') {
      const which = args.positional[1] ?? 'github-action';
      if (which !== 'github-action') {
        process.stderr.write(
          `Unknown scaffold "${which}". Available: github-action\n`,
        );
        return 2;
      }
      const body = renderGithubActionYaml(scaffoldOptionsFromArgs(args));
      process.stdout.write(body);
      return 0;
    }
    if (args.positional[0] === 'render-comment') {
      return runRenderComment(args);
    }
    if (args.positional[0] === 'packet') {
      return runPacket(args);
    }
    const inspection = await inspectSharkcraft({ cwd: resolveCwd(args) });
    const since = flagString(args, 'since');
    const files = flagList(args, 'files');
    const packet = buildReviewPacket(inspection, {
      ...(since ? { since } : {}),
      ...(flagBool(args, 'staged') ? { staged: true } : {}),
      ...(files.length ? { files } : {}),
    });
    if (flagBool(args, 'json')) {
      process.stdout.write(asJson(packet) + '\n');
      return 0;
    }
    process.stdout.write(header('Review packet'));
    process.stdout.write(kv('changed files', String(packet.changedFiles.length)) + '\n');
    process.stdout.write(kv('affected paths', String(packet.affectedPaths.length)) + '\n');
    process.stdout.write(
      kv('boundary violations', String(packet.boundaryViolations.length)) + '\n\n',
    );
    if (packet.changedFiles.length === 0) {
      process.stdout.write('No changed files detected. Try `--since HEAD~1` or `--staged`.\n');
      return 0;
    }
    process.stdout.write('Changed files:\n');
    for (const f of packet.changedFiles.slice(0, 10)) process.stdout.write(`  • ${f}\n`);
    if (packet.changedFiles.length > 10) {
      process.stdout.write(`  … (${packet.changedFiles.length - 10} more)\n`);
    }
    if (packet.relevantRules.length) {
      process.stdout.write('\nRelevant rules:\n');
      for (const r of packet.relevantRules) process.stdout.write(`  • ${r.id} — ${r.title}\n`);
    }
    if (packet.relevantTemplates.length) {
      process.stdout.write('\nRelevant templates:\n');
      for (const t of packet.relevantTemplates) process.stdout.write(`  • ${t.id} ${t.name}\n`);
    }
    if (packet.boundaryViolations.length) {
      process.stdout.write('\nBoundary violations in this change set:\n');
      for (const v of packet.boundaryViolations) {
        process.stdout.write(
          `  ${v.severity.toUpperCase().padEnd(8)} ${v.file}:${v.line}  ${v.importSpecifier}  (${v.ruleId})\n`,
        );
      }
    }
    if (packet.missingTestsHeuristic.length) {
      process.stdout.write('\nMissing tests heuristic:\n');
      for (const m of packet.missingTestsHeuristic) process.stdout.write(`  • ${m}\n`);
    }
    if (packet.verificationCommands.length) {
      process.stdout.write('\nVerification commands:\n');
      for (const c of packet.verificationCommands) process.stdout.write(`  $ ${c}\n`);
    }
    process.stdout.write('\n' + packet.reviewerInstructions + '\n');
    return 0;
  },
};

async function runRenderComment(args: ParsedArgs): Promise<number> {
  const inputPath = args.positional[1];
  if (!inputPath) {
    process.stderr.write(
      'Usage: shrk review render-comment <packet.json> [--output <file>] [--title <title>]\n',
    );
    return 2;
  }
  const full = nodePath.isAbsolute(inputPath)
    ? inputPath
    : nodePath.resolve(resolveCwd(args), inputPath);
  if (!existsSync(full)) {
    process.stderr.write(`Review packet not found: ${full}\n`);
    return 2;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(full, 'utf8'));
  } catch (err) {
    process.stderr.write(
      `Failed to parse review packet as JSON: ${(err as Error).message}\n`,
    );
    return 2;
  }
  // Auto-detect v3 first, then v2.
  if (isReviewPacketV3Shape(parsed)) {
    const format = (flagString(args, 'format') ?? 'markdown') as 'markdown' | 'html';
    const maxFiles = flagNumber(args, 'max-files');
    const maxItems = flagNumber(args, 'max-items');
    const out = renderReviewCommentV3(parsed as IReviewPacketV3, {
      format,
      ...(maxFiles !== undefined ? { maxFiles } : {}),
      ...(maxItems !== undefined ? { maxItems } : {}),
    });
    const output = flagString(args, 'output');
    if (output) {
      const outFull = nodePath.isAbsolute(output)
        ? output
        : nodePath.resolve(resolveCwd(args), output);
      writeFileSync(outFull, out, 'utf8');
      process.stdout.write(`Wrote ${out.length} bytes to ${outFull}\n`);
    } else {
      process.stdout.write(out);
    }
    return 0;
  }
  // Auto-detect v2 schema and use the v2 renderer.
  if (isReviewPacketV2Shape(parsed)) {
    const format = flagString(args, 'format') as 'github' | 'gitlab' | 'markdown' | 'html' | undefined;
    const maxFiles = flagNumber(args, 'max-files');
    const maxItems = flagNumber(args, 'max-items');
    const md = renderReviewCommentV2(parsed as IReviewPacketV2, {
      ...(format ? { format } : {}),
      ...(maxFiles !== undefined ? { maxFiles } : {}),
      ...(maxItems !== undefined ? { maxItems } : {}),
    });
    const output = flagString(args, 'output');
    if (output) {
      const outFull = nodePath.isAbsolute(output)
        ? output
        : nodePath.resolve(resolveCwd(args), output);
      writeFileSync(outFull, md, 'utf8');
      process.stdout.write(`Wrote ${md.length} bytes to ${outFull}\n`);
    } else {
      process.stdout.write(md);
    }
    return 0;
  }
  if (!isReviewPacketShape(parsed)) {
    process.stderr.write(
      'Input does not look like a review packet (missing expected fields).\n',
    );
    return 2;
  }
  const title = flagString(args, 'title');
  const format = flagString(args, 'format') as 'github' | 'markdown' | undefined;
  const maxFiles = flagNumber(args, 'max-files');
  const maxRules = flagNumber(args, 'max-rules');
  const includeBoundaries = flagBool(args, 'include-boundaries');
  const includeCoverage = flagBool(args, 'include-coverage');
  const includeDrift = flagBool(args, 'include-drift');
  const collapseLong = flagBool(args, 'collapse-long-sections');
  const boundariesArtifact = readArtifact(args, 'boundaries');
  const coverageArtifact = readArtifact(args, 'coverage');
  const driftArtifact = readArtifact(args, 'drift');
  const md = renderReviewComment(parsed as IReviewPacket, {
    ...(title ? { title } : {}),
    ...(format ? { format } : {}),
    ...(maxFiles !== undefined ? { maxFiles } : {}),
    ...(maxRules !== undefined ? { maxRules } : {}),
    includeBoundaries: includeBoundaries !== false ? true : false,
    ...(includeCoverage ? { includeCoverage: true } : {}),
    ...(includeDrift ? { includeDrift: true } : {}),
    ...(collapseLong ? { collapseLongSections: true } : {}),
    ...(boundariesArtifact ? { boundariesArtifact } : {}),
    ...(coverageArtifact ? { coverageArtifact } : {}),
    ...(driftArtifact ? { driftArtifact } : {}),
  });
  const output = flagString(args, 'output');
  if (output) {
    const outFull = nodePath.isAbsolute(output)
      ? output
      : nodePath.resolve(resolveCwd(args), output);
    writeFileSync(outFull, md, 'utf8');
    process.stdout.write(`Wrote ${md.length} bytes to ${outFull}\n`);
  } else {
    process.stdout.write(md);
  }
  return 0;
}

function readArtifact(args: ParsedArgs, name: string): Record<string, unknown> | undefined {
  const flag = flagString(args, name);
  if (!flag) return undefined;
  const full = nodePath.isAbsolute(flag) ? flag : nodePath.resolve(resolveCwd(args), flag);
  if (!existsSync(full)) {
    process.stderr.write(`--${name} artifact not found: ${full}\n`);
    return undefined;
  }
  try {
    return JSON.parse(readFileSync(full, 'utf8')) as Record<string, unknown>;
  } catch (e) {
    process.stderr.write(`Failed to parse --${name} artifact: ${(e as Error).message}\n`);
    return undefined;
  }
}

function isReviewPacketShape(v: unknown): v is IReviewPacket {
  if (typeof v !== 'object' || v === null) return false;
  const p = v as Record<string, unknown>;
  return (
    Array.isArray(p.changedFiles) &&
    Array.isArray(p.boundaryViolations) &&
    Array.isArray(p.verificationCommands)
  );
}

function isReviewPacketV2Shape(v: unknown): boolean {
  if (typeof v !== 'object' || v === null) return false;
  return (v as { schema?: string }).schema === REVIEW_PACKET_V2_SCHEMA;
}

function isReviewPacketV3Shape(v: unknown): boolean {
  if (typeof v !== 'object' || v === null) return false;
  return (v as { schema?: string }).schema === REVIEW_PACKET_V3_SCHEMA;
}

async function runPacket(args: ParsedArgs): Promise<number> {
  const inspection = await inspectSharkcraft({ cwd: resolveCwd(args) });
  const since = flagString(args, 'since');
  const files = flagList(args, 'files');
  const v2 = flagBool(args, 'v2');
  const baselineFile = flagString(args, 'quality-baseline');
  const fmt = flagString(args, 'format') ?? 'json';
  if (flagBool(args, 'v3')) {
    const bundleId = flagString(args, 'bundle');
    const packet = await buildReviewPacketV3(inspection, {
      ...(since ? { since } : {}),
      ...(flagBool(args, 'staged') ? { staged: true } : {}),
      ...(files.length ? { files } : {}),
      ...(baselineFile ? { qualityBaselineFile: baselineFile } : {}),
      ...(bundleId ? { bundleId } : {}),
    });
    if (fmt === 'markdown') {
      process.stdout.write(renderReviewCommentV3(packet, { format: 'markdown' }));
    } else if (fmt === 'html') {
      process.stdout.write(renderReviewCommentV3(packet, { format: 'html' }));
    } else {
      process.stdout.write(asJson(packet) + '\n');
    }
    return 0;
  }
  if (v2) {
    const packet = await buildReviewPacketV2(inspection, {
      ...(since ? { since } : {}),
      ...(flagBool(args, 'staged') ? { staged: true } : {}),
      ...(files.length ? { files } : {}),
      ...(baselineFile ? { qualityBaselineFile: baselineFile } : {}),
    });
    if (fmt === 'markdown') {
      process.stdout.write(renderReviewCommentV2(packet, { format: 'markdown' }));
    } else if (fmt === 'html') {
      process.stdout.write(renderReviewCommentV2(packet, { format: 'html' }));
    } else {
      process.stdout.write(asJson(packet) + '\n');
    }
    return 0;
  }
  const packet = buildReviewPacket(inspection, {
    ...(since ? { since } : {}),
    ...(flagBool(args, 'staged') ? { staged: true } : {}),
    ...(files.length ? { files } : {}),
  });
  if (fmt === 'markdown' || fmt === 'html') {
    process.stdout.write(renderReviewComment(packet));
  } else {
    process.stdout.write(asJson(packet) + '\n');
  }
  return 0;
}
