// Inferred pipelines draft — generated by `shrk onboard`. Review before adopting.
// Move keepers into sharkcraft/pipelines.ts.
export default [
  {
    id: "unit-test",
    title: "Unit test pipeline",
    description: "Pick a focused unit under test and write/run the spec.",
    steps: [
      { id: "pick-target", title: "pick-target" },
      { id: "write-spec", title: "write-spec" },
      { id: "run-tests", title: "run-tests" }
    ],
    // reason: test runner detected
  },
  {
    id: "safe-generation",
    title: "Safe generation pipeline",
    description: "Use `shrk gen --dry-run --save-plan` → review → `shrk apply --verify-signature` for risky writes.",
    steps: [
      { id: "plan", title: "plan" },
      { id: "review", title: "review" },
      { id: "apply", title: "apply" }
    ],
    // reason: TypeScript project — codegen flows benefit from plan review
  },
  {
    id: "feature-dev",
    title: "Feature development pipeline",
    description: "Implement a new feature: plan → scaffold → wire → test → verify.",
    steps: [
      { id: "plan", title: "plan" },
      { id: "scaffold", title: "scaffold" },
      { id: "wire-up", title: "wire-up" },
      { id: "add-tests", title: "add-tests" },
      { id: "verify", title: "verify" }
    ],
    // reason: src/ + test runner present
  },
  {
    id: "release-check",
    title: "Release readiness pipeline",
    description: "Typecheck → lint → tests → build → boundary scan.",
    steps: [
      { id: "typecheck", title: "typecheck" },
      { id: "lint", title: "lint" },
      { id: "test", title: "test" },
      { id: "build", title: "build" },
      { id: "boundaries", title: "boundaries" }
    ],
    // reason: build + test scripts present
  },
];
