// Inferred rules draft — generated by `shrk onboard`. Review before adopting.
// Move keepers into sharkcraft/rules.ts.
export default [
  {
    id: "project.package-manager",
    type: 'rule',
    title: "Use bun for install/run",
    priority: "medium",
    content: "This repo uses bun. Run scripts with `bun run <script>`.",
    tags: ["inferred", "package-json"],
    // reason: inferred from project signals (has-bun profile)
  },
  {
    id: "typescript.strict-mode",
    type: 'rule',
    title: "TypeScript strict mode enabled",
    priority: "high",
    content: "TypeScript strict mode is enabled. Keep it that way — do not weaken `strict` to land code.",
    tags: ["inferred", "tsconfig"],
    // reason: tsconfig strict=true
  },
  {
    id: "testing.runner",
    type: 'rule',
    title: "Run tests with `bun test`",
    priority: "medium",
    content: "Tests are executed via `bun test`. Use `bun test <path>` to run a single file.",
    tags: ["inferred", "package-json"],
    // reason: bun test script detected
  },
];
