// Inferred boundary rules draft — generated by `shrk onboard`. Review before adopting.
// Drop into sharkcraft/boundaries.ts (and register via sharkcraft.config.ts boundaryFiles).
export default [
];
