// Inferred path conventions draft — generated by `shrk onboard`. Review before adopting.
// Move keepers into sharkcraft/paths.ts.
export default [
  {
    id: "paths.src",
    type: 'path',
    title: "Application source under src/",
    content: "Application source code lives in src/. Avoid sibling top-level directories that duplicate src/ semantics.",
    patterns: ["src/**"],
    tags: ["inferred", "path"],
    // reason: src/ directory present
  },
  {
    id: "paths.services",
    type: 'path',
    title: "Services in src/services/",
    content: "Services live under src/services/ and follow the `*.service.ts` naming pattern.",
    patterns: ["src/services/**", "**/*.service.ts"],
    tags: ["inferred", "path"],
    // reason: src/services/ directory present
  },
  {
    id: "paths.utils",
    type: 'path',
    title: "Utilities in src/utils/",
    content: "Pure utility functions live in src/utils/. One construct per file.",
    patterns: ["src/utils/**"],
    tags: ["inferred", "path"],
    // reason: src/utils/ directory present
  },
  {
    id: "paths.tests",
    type: 'path',
    title: "Tests live in tests/",
    content: "Test files live in tests/, mirroring src/. Use the *.spec.ts / *.test.ts suffix.",
    patterns: ["tests/**", "**/*.spec.ts", "**/*.test.ts"],
    tags: ["inferred", "path"],
    // reason: tests/ directory present
  },
];
