// Inferred template candidates — generated by `shrk onboard`.
// NOT runnable until you fill in targetPath + content. Re-run with `--scaffold-templates` to draft bodies.
export default [
  {
    id: "inferred.service",
    name: "Service",
    description: "New service file under src/services/.",
    confidence: "high",
    // targetPath hint: src/services/<name>.service.ts
    // sample: src/services/billing.service.ts
    // reason: 3 matching file(s) found
  },
  {
    id: "inferred.util",
    name: "Utility",
    description: "New utility module under src/utils/.",
    confidence: "medium",
    // targetPath hint: src/utils/<name>.util.ts
    // sample: src/utils/format.util.ts
    // reason: 2 matching file(s) found
  },
  {
    id: "inferred.spec",
    name: "Spec / test file",
    description: "New spec/test file colocated with source.",
    confidence: "medium",
    // targetPath hint: src/<area>/<name>.spec.ts
    // sample: tests/format.spec.ts
    // reason: 2 matching file(s) found
  },
];
