import { describe, expect, test } from 'bun:test';
import {
  renderReviewComment,
  type IReviewPacket,
} from '../index.ts';

function makePacket(overrides: Partial<IReviewPacket> = {}): IReviewPacket {
  return {
    changedFiles: ['src/services/user.service.ts', 'docs/readme.md'],
    affectedPaths: ['paths.services'],
    relevantRules: [
      { id: 'typescript.strict-mode', title: 'TS strict mode', reason: 'tsconfig' },
    ],
    relevantTemplates: [{ id: 'inferred.service', name: 'Service' }],
    relevantPipelines: [{ id: 'feature-dev', title: 'Feature development' }],
    boundaryViolations: [
      {
        ruleId: 'architecture.core.no-imports-up',
        file: 'src/services/user.service.ts',
        importSpecifier: '@app/kernel',
        line: 12,
        severity: 'error',
        message: 'core must not import kernel',
      },
    ],
    missingTestsHeuristic: ['src/services/user.service.ts → expected tests/user.service.spec.ts'],
    verificationCommands: ['bun test', 'shrk doctor'],
    reviewerInstructions: '# AI reviewer instructions\n\nCheck the boundary violation.',
    ...overrides,
  };
}

describe('renderReviewComment', () => {
  test('includes the standard sections', () => {
    const md = renderReviewComment(makePacket());
    expect(md).toContain('## SharkCraft review');
    expect(md).toContain('### Changed files');
    expect(md).toContain('### Risks');
    expect(md).toContain('### Boundary issues');
    expect(md).toContain('### Suggested checks');
    expect(md).toContain('### AI reviewer instructions');
    expect(md).toContain('Generated by `shrk review render-comment`');
  });

  test('lists each changed file', () => {
    const md = renderReviewComment(makePacket());
    expect(md).toContain('`src/services/user.service.ts`');
    expect(md).toContain('`docs/readme.md`');
  });

  test('renders boundary violations with rule id and severity', () => {
    const md = renderReviewComment(makePacket());
    expect(md).toContain('ERROR');
    expect(md).toContain('architecture.core.no-imports-up');
    expect(md).toContain('@app/kernel');
  });

  test('omits reviewer instructions when option disables them', () => {
    const md = renderReviewComment(makePacket(), {
      includeReviewerInstructions: false,
    });
    expect(md).not.toContain('### AI reviewer instructions');
  });

  test('handles empty packet gracefully', () => {
    const md = renderReviewComment(
      makePacket({
        changedFiles: [],
        boundaryViolations: [],
        missingTestsHeuristic: [],
        relevantRules: [],
        verificationCommands: [],
      }),
    );
    expect(md).toContain('_No changed files detected._');
    expect(md).toContain('_No boundary violations in the change set._');
    expect(md).toContain('_No verification commands configured._');
  });

  test('allows a custom title', () => {
    const md = renderReviewComment(makePacket(), { title: 'Custom heading' });
    expect(md).toContain('## Custom heading');
  });
});
