import type { IInterpolatedPipeline } from './interpolate.ts';

const WRITE_STEP_TYPES = new Set(['apply-plan']);

/**
 * Render a copy-pasteable shell script from an interpolated pipeline. The
 * script:
 *  - sets `set -euo pipefail` at the top so failures stop the chain
 *  - prefixes each step with a `# === N. step-id ===` header
 *  - emits CLI commands verbatim (already interpolated)
 *  - skips steps marked `skipped`
 *  - inserts an "echo + manual confirm" stanza in front of write/apply steps
 *  - leaves agent / mcp-tool steps as no-op `echo` lines (those are agent
 *    actions, not shell commands)
 */
export function renderPipelineScript(pipeline: IInterpolatedPipeline): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# Generated by `shrk pipelines script`.');
  lines.push(`# Pipeline: ${pipeline.id} — ${pipeline.title}`);
  lines.push(`# Task: ${pipeline.task}`);
  lines.push('set -euo pipefail');
  lines.push('');

  let stepIndex = 0;
  for (const step of pipeline.steps) {
    stepIndex += 1;
    if (step.skipped) {
      lines.push(`# === ${stepIndex}. ${step.id} (skipped — optional, not included) ===`);
      lines.push('');
      continue;
    }
    const reviewTag = step.humanReview ? ' [HUMAN REVIEW]' : '';
    const optionalTag = step.required ? '' : ' (optional)';
    lines.push(`# === ${stepIndex}. [${step.type}] ${step.id}${optionalTag}${reviewTag} ===`);
    if (step.description) lines.push(`# ${step.description.replace(/\n/g, '\n# ')}`);
    if (step.instruction) lines.push(`# instruction: ${step.instruction.replace(/\n/g, '\n# ')}`);
    if (step.references.length) {
      lines.push(`# references: ${step.references.join(', ')}`);
    }
    if (step.mcpTools.length) {
      lines.push(`# mcpTools: ${step.mcpTools.join(', ')}`);
    }
    if (WRITE_STEP_TYPES.has(step.type)) {
      lines.push('echo "About to write files. Confirm by pressing Enter, or Ctrl-C to abort."');
      lines.push('read -r _');
    }
    if (step.cliCommands.length === 0 && step.type !== 'command' && step.type !== 'apply-plan') {
      // Agent-only step: emit an echo so the script remains valid but no-op.
      lines.push(`echo "→ ${step.id}: agent/mcp action — no shell command"`);
    }
    for (const cmd of step.cliCommands) {
      lines.push(cmd);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Find the next required, not-yet-marked-done step. Useful for an agent or
 * the CLI that wants to ask "what should I do now?".
 */
export function findNextStep(pipeline: IInterpolatedPipeline): IInterpolatedPipeline['steps'][number] | null {
  for (const step of pipeline.steps) {
    if (step.skipped) continue;
    return step;
  }
  return null;
}
