import type { IFeatureBundle, IFeatureBundleValidation } from './feature-bundle.ts';

export interface IRenderBundleValidationHtmlOptions {
  baselineComparison?: unknown;
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Render an HTML validation report for a bundle. Self-contained (inline
 * styles); no external assets. Designed to be uploaded by CI as a build
 * artifact and viewed offline.
 */
export function renderBundleValidationHtml(
  bundle: IFeatureBundle,
  validation: IFeatureBundleValidation,
  options: IRenderBundleValidationHtmlOptions = {},
): string {
  const parts: string[] = [];
  parts.push('<!doctype html>');
  parts.push('<html><head><meta charset="utf-8">');
  parts.push(`<title>SharkCraft bundle validation — ${esc(bundle.id)}</title>`);
  parts.push('<style>');
  parts.push(
    'body{font:14px/1.4 -apple-system,BlinkMacSystemFont,sans-serif;max-width:1080px;margin:24px auto;padding:0 16px;color:#1f2328;}',
  );
  parts.push('h1{font-size:20px;border-bottom:1px solid #d0d7de;padding-bottom:8px;}');
  parts.push('h2{font-size:16px;margin-top:24px;}');
  parts.push('table{border-collapse:collapse;width:100%;margin:8px 0;}');
  parts.push('th,td{border:1px solid #d0d7de;padding:6px 10px;text-align:left;}');
  parts.push('th{background:#f6f8fa;}');
  parts.push('code,pre{background:#f6f8fa;padding:1px 4px;border-radius:4px;font-size:12px;}');
  parts.push('.tag{display:inline-block;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;}');
  parts.push('.tag.ok{background:#dafbe1;color:#1a7f37;}');
  parts.push('.tag.fail{background:#ffebe9;color:#cf222e;}');
  parts.push('.tag.warn{background:#fff8c5;color:#9a6700;}');
  parts.push('</style></head><body>');

  parts.push(`<h1>Bundle validation — ${esc(bundle.id)}</h1>`);
  parts.push(`<p><strong>Task:</strong> ${esc(bundle.task)}</p>`);
  parts.push(
    `<p><strong>Result:</strong> <span class="tag ${validation.passed ? 'ok' : 'fail'}">${validation.passed ? 'PASSED' : 'FAILED'}</span></p>`,
  );
  parts.push(`<p>Started: ${esc(validation.startedAt)} — Finished: ${esc(validation.finishedAt)} — Warnings: ${validation.warnings}</p>`);

  parts.push(`<h2>Gate matrix (${validation.commandsRun.length})</h2>`);
  parts.push('<table><thead><tr><th>Gate</th><th>Result</th><th>Note</th></tr></thead><tbody>');
  for (const c of validation.commandsRun) {
    parts.push(
      `<tr><td><code>${esc(c.command)}</code></td><td><span class="tag ${c.passed ? 'ok' : 'fail'}">${c.passed ? 'OK' : 'FAIL'}</span></td><td>${esc(c.note ?? '')}</td></tr>`,
    );
  }
  parts.push('</tbody></table>');

  parts.push(`<h2>Plans (${bundle.plans.length})</h2>`);
  parts.push('<table><thead><tr><th>Name</th><th>Template</th><th>Status</th><th>Targets</th></tr></thead><tbody>');
  for (const p of bundle.plans) {
    parts.push(
      `<tr><td><code>${esc(p.name)}</code></td><td>${esc(p.templateId)}</td><td>${esc(p.status)}</td><td>${esc(p.expectedTargets.join(', '))}</td></tr>`,
    );
  }
  parts.push('</tbody></table>');

  if (bundle.dependencies.length > 0) {
    parts.push(`<h2>Dependencies (${bundle.dependencies.length})</h2><ul>`);
    for (const d of bundle.dependencies)
      parts.push(`<li><code>${esc(d.from)}</code> → <code>${esc(d.to)}</code> — ${esc(d.reason)}</li>`);
    parts.push(`</ul>`);
  }

  if (options.baselineComparison) {
    parts.push('<h2>Quality baseline comparison</h2>');
    parts.push(`<pre>${esc(JSON.stringify(options.baselineComparison, null, 2))}</pre>`);
  }

  parts.push('<p><em>Generated by SharkCraft bundle validate v2.</em></p>');
  parts.push('</body></html>');
  return parts.join('\n') + '\n';
}
