/**
 * Deterministic GitHub Actions scaffolds for SharkCraft. The CLI commands
 * stay dry-run by default; this module only renders YAML strings.
 *
 * Two surfaces:
 *  - `renderQualityCiWorkflow` — selectable gates (quality / policy / impact
 *    / review / report-site / bundle-replay / node-compat).
 *  - `renderBundleReplayWorkflow` — scheduled cross-bundle replay job.
 */

export const CI_SCAFFOLD_SCHEMA = 'sharkcraft.ci-scaffold/v1';

export interface ICiScaffoldOptions {
  withQuality?: boolean;
  withPolicy?: boolean;
  withImpact?: boolean;
  withReview?: boolean;
  withReportSite?: boolean;
  withBundleReplay?: boolean;
  withNodeCompat?: boolean;
  /** Include a `shrk release readiness` gate step. */
  withReleaseReadiness?: boolean;
  bunVersion?: string;
  name?: string;
}

export type BundleReplaySchedule = 'weekly' | 'daily' | 'manual';

export interface IBundleReplayScaffoldOptions {
  schedule?: BundleReplaySchedule;
  withReportSite?: boolean;
  name?: string;
  bunVersion?: string;
}

export interface ICiProviderScaffoldExtras {
  withPolicySnapshotGate?: boolean;
  /** Include a `shrk release readiness` gate step. */
  withReleaseReadiness?: boolean;
}

function header(name: string): string {
  return [
    `# SharkCraft CI scaffold — generated by \`shrk ci scaffold github-actions\`.`,
    `# Edit by hand if you outgrow the defaults; SharkCraft will not regenerate without --force.`,
    `name: ${name}`,
    `on:`,
    `  push:`,
    `    branches: [main]`,
    `  pull_request:`,
    `    branches: [main]`,
  ].join('\n');
}

function setup(bunVersion: string): string {
  return [
    '      - uses: actions/checkout@v4',
    '      - uses: oven-sh/setup-bun@v1',
    `        with: { bun-version: '${bunVersion}' }`,
    '      - run: bun install --frozen-lockfile',
  ].join('\n');
}

export function renderQualityCiWorkflow(options: ICiScaffoldOptions = {}): string {
  const name = options.name ?? 'SharkCraft CI';
  const bun = options.bunVersion ?? '1.1.0';
  const lines: string[] = [];
  lines.push(header(name));
  lines.push('jobs:');
  lines.push('  sharkcraft:');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    timeout-minutes: 20');
  lines.push('    steps:');
  lines.push(setup(bun));
  lines.push("      - name: SharkCraft doctor");
  lines.push("        run: bun run shrk doctor");
  if (options.withQuality) {
    lines.push("      - name: Quality gate");
    lines.push("        run: bun run shrk quality --ci");
  }
  if (options.withPolicy) {
    lines.push("      - name: Policy run");
    lines.push("        run: bun run shrk policy run --json > .sharkcraft/reports/policy.json");
    lines.push("      - name: Policy snapshot gate");
    lines.push("        run: bun run shrk policy snapshot --all --gate --json > .sharkcraft/reports/policy-snapshots.json || true");
  }
  if (options.withImpact) {
    lines.push("      - name: Impact (since origin/main)");
    lines.push("        run: |");
    lines.push("          mkdir -p .sharkcraft/reports");
    lines.push("          bun run shrk impact --since origin/main --format json > .sharkcraft/reports/impact.json || true");
  }
  if (options.withReview) {
    lines.push("      - name: Review packet v3");
    lines.push("        run: bun run shrk review packet --v3 --since origin/main --json > .sharkcraft/reports/review.json || true");
  }
  if (options.withBundleReplay) {
    lines.push("      - name: Bundle replay (all)");
    lines.push("        run: bun run shrk bundle replay --all --report --html || true");
  }
  if (options.withReportSite) {
    lines.push("      - name: Build static report site");
    lines.push("        run: bun run shrk report site --output .sharkcraft/reports/site || true");
  }
  if (options.withNodeCompat) {
    lines.push("      - name: compat:node audit");
    lines.push("        run: bun run compat:node --json > .sharkcraft/reports/compat-node.json || true");
  }
  if (options.withReleaseReadiness) {
    lines.push("      - name: Release readiness gate");
    lines.push("        run: bun run shrk release readiness --json > .sharkcraft/reports/release-readiness.json");
  }
  lines.push("      - name: Upload SharkCraft reports");
  lines.push("        if: always()");
  lines.push("        uses: actions/upload-artifact@v4");
  lines.push("        with:");
  lines.push("          name: sharkcraft-reports");
  lines.push("          path: |");
  lines.push("            .sharkcraft/reports/**");
  lines.push("            .sharkcraft/bundles/*/reports/**");
  lines.push("          if-no-files-found: ignore");
  return lines.join('\n') + '\n';
}

function scheduleCron(s: BundleReplaySchedule): string {
  if (s === 'daily') return "    - cron: '17 6 * * *'";
  if (s === 'weekly') return "    - cron: '17 6 * * 1'";
  return '';
}

export type CiProvider = 'github-actions' | 'gitlab' | 'bitbucket';

export interface ICiProviderScaffoldOptions extends ICiScaffoldOptions, ICiProviderScaffoldExtras {}

export function renderGitlabCiWorkflow(options: ICiProviderScaffoldOptions = {}): string {
  const bun = options.bunVersion ?? '1.1.0';
  const lines: string[] = [];
  lines.push('# SharkCraft CI scaffold — generated by `shrk ci scaffold gitlab`.');
  lines.push('# Edit by hand if you outgrow the defaults; SharkCraft will not regenerate without --force.');
  lines.push('');
  lines.push('stages:');
  lines.push('  - sharkcraft_quality');
  lines.push('  - sharkcraft_review');
  lines.push('  - sharkcraft_reports');
  lines.push('');
  lines.push('default:');
  lines.push(`  image: oven/bun:${bun}`);
  lines.push('  before_script:');
  lines.push('    - bun install --frozen-lockfile');
  lines.push('');
  lines.push('sharkcraft:doctor:');
  lines.push('  stage: sharkcraft_quality');
  lines.push('  script:');
  lines.push('    - bun run shrk doctor');
  if (options.withQuality) {
    lines.push('');
    lines.push('sharkcraft:quality:');
    lines.push('  stage: sharkcraft_quality');
    lines.push('  script:');
    lines.push('    - bun run shrk quality --ci');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withPolicy) {
    lines.push('');
    lines.push('sharkcraft:policy:');
    lines.push('  stage: sharkcraft_quality');
    lines.push('  script:');
    lines.push('    - mkdir -p .sharkcraft/reports');
    lines.push('    - bun run shrk policy run --json > .sharkcraft/reports/policy.json');
    if (options.withPolicySnapshotGate) {
      lines.push('    - bun run shrk policy snapshot --all --gate --json > .sharkcraft/reports/policy-snapshots.json || true');
    }
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withImpact) {
    lines.push('');
    lines.push('sharkcraft:impact:');
    lines.push('  stage: sharkcraft_review');
    lines.push('  script:');
    lines.push('    - mkdir -p .sharkcraft/reports');
    lines.push('    - bun run shrk impact --since $CI_DEFAULT_BRANCH --format json > .sharkcraft/reports/impact.json || true');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withReview) {
    lines.push('');
    lines.push('sharkcraft:review:');
    lines.push('  stage: sharkcraft_review');
    lines.push('  script:');
    lines.push('    - mkdir -p .sharkcraft/reports');
    lines.push('    - bun run shrk review packet --v3 --since $CI_DEFAULT_BRANCH --json > .sharkcraft/reports/review.json || true');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withBundleReplay) {
    lines.push('');
    lines.push('sharkcraft:bundle-replay:');
    lines.push('  stage: sharkcraft_reports');
    lines.push('  script:');
    lines.push('    - bun run shrk bundle replay --all --report --html || true');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withReportSite) {
    lines.push('');
    lines.push('sharkcraft:report-site:');
    lines.push('  stage: sharkcraft_reports');
    lines.push('  script:');
    lines.push('    - bun run shrk report site --output .sharkcraft/reports/site || true');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/site/');
  }
  if (options.withNodeCompat) {
    lines.push('');
    lines.push('sharkcraft:compat-node:');
    lines.push('  stage: sharkcraft_quality');
    lines.push('  script:');
    lines.push('    - bun run compat:node --json > .sharkcraft/reports/compat-node.json || true');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  if (options.withReleaseReadiness) {
    lines.push('');
    lines.push('sharkcraft:release-readiness:');
    lines.push('  stage: sharkcraft_reports');
    lines.push('  script:');
    lines.push('    - bun run shrk release readiness --json > .sharkcraft/reports/release-readiness.json');
    lines.push('  artifacts:');
    lines.push('    when: always');
    lines.push('    paths:');
    lines.push('      - .sharkcraft/reports/');
  }
  return lines.join('\n') + '\n';
}

export function renderBitbucketCiWorkflow(options: ICiProviderScaffoldOptions = {}): string {
  const bun = options.bunVersion ?? '1.1.0';
  const lines: string[] = [];
  lines.push('# SharkCraft CI scaffold — generated by `shrk ci scaffold bitbucket`.');
  lines.push('# Edit by hand if you outgrow the defaults; SharkCraft will not regenerate without --force.');
  lines.push('');
  lines.push(`image: oven/bun:${bun}`);
  lines.push('');
  lines.push('definitions:');
  lines.push('  steps:');
  lines.push('    - step: &sharkcraft-doctor');
  lines.push('        name: SharkCraft doctor');
  lines.push('        script:');
  lines.push('          - bun install --frozen-lockfile');
  lines.push('          - bun run shrk doctor');
  if (options.withQuality) {
    lines.push('    - step: &sharkcraft-quality');
    lines.push('        name: SharkCraft quality');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - bun run shrk quality --ci');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withPolicy) {
    lines.push('    - step: &sharkcraft-policy');
    lines.push('        name: SharkCraft policy');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - mkdir -p .sharkcraft/reports');
    lines.push('          - bun run shrk policy run --json > .sharkcraft/reports/policy.json');
    if (options.withPolicySnapshotGate) {
      lines.push('          - bun run shrk policy snapshot --all --gate --json > .sharkcraft/reports/policy-snapshots.json || true');
    }
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withImpact) {
    lines.push('    - step: &sharkcraft-impact');
    lines.push('        name: SharkCraft impact');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - mkdir -p .sharkcraft/reports');
    lines.push('          - bun run shrk impact --since origin/main --format json > .sharkcraft/reports/impact.json || true');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withReview) {
    lines.push('    - step: &sharkcraft-review');
    lines.push('        name: SharkCraft review');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - mkdir -p .sharkcraft/reports');
    lines.push('          - bun run shrk review packet --v3 --since origin/main --json > .sharkcraft/reports/review.json || true');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withReportSite) {
    lines.push('    - step: &sharkcraft-report-site');
    lines.push('        name: SharkCraft report site');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - bun run shrk report site --output .sharkcraft/reports/site || true');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/site/**');
  }
  if (options.withBundleReplay) {
    lines.push('    - step: &sharkcraft-bundle-replay');
    lines.push('        name: SharkCraft bundle replay');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - bun run shrk bundle replay --all --report --html || true');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withNodeCompat) {
    lines.push('    - step: &sharkcraft-compat-node');
    lines.push('        name: SharkCraft compat:node');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - bun run compat:node --json > .sharkcraft/reports/compat-node.json || true');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  if (options.withReleaseReadiness) {
    lines.push('    - step: &sharkcraft-release-readiness');
    lines.push('        name: SharkCraft release readiness');
    lines.push('        script:');
    lines.push('          - bun install --frozen-lockfile');
    lines.push('          - bun run shrk release readiness --json > .sharkcraft/reports/release-readiness.json');
    lines.push('        artifacts:');
    lines.push('          - .sharkcraft/reports/**');
  }
  lines.push('');
  lines.push('pipelines:');
  lines.push('  pull-requests:');
  lines.push('    "**":');
  lines.push('      - step: *sharkcraft-doctor');
  if (options.withQuality) lines.push('      - step: *sharkcraft-quality');
  if (options.withPolicy) lines.push('      - step: *sharkcraft-policy');
  if (options.withImpact) lines.push('      - step: *sharkcraft-impact');
  if (options.withReview) lines.push('      - step: *sharkcraft-review');
  if (options.withReportSite) lines.push('      - step: *sharkcraft-report-site');
  if (options.withBundleReplay) lines.push('      - step: *sharkcraft-bundle-replay');
  if (options.withNodeCompat) lines.push('      - step: *sharkcraft-compat-node');
  if (options.withReleaseReadiness) lines.push('      - step: *sharkcraft-release-readiness');
  lines.push('');
  lines.push('  custom:');
  lines.push('    sharkcraft-governance:');
  lines.push('      - step: *sharkcraft-doctor');
  if (options.withQuality) lines.push('      - step: *sharkcraft-quality');
  if (options.withPolicy) lines.push('      - step: *sharkcraft-policy');
  if (options.withBundleReplay) lines.push('      - step: *sharkcraft-bundle-replay');
  if (options.withReportSite) lines.push('      - step: *sharkcraft-report-site');
  if (options.withReleaseReadiness) lines.push('      - step: *sharkcraft-release-readiness');
  return lines.join('\n') + '\n';
}

export function renderCiWorkflow(
  provider: CiProvider,
  options: ICiProviderScaffoldOptions = {},
): string {
  if (provider === 'gitlab') return renderGitlabCiWorkflow(options);
  if (provider === 'bitbucket') return renderBitbucketCiWorkflow(options);
  return renderQualityCiWorkflow(options);
}

export function defaultCiOutputPath(provider: CiProvider | 'jenkins' | 'azure'): string {
  if (provider === 'gitlab') return '.gitlab-ci.yml';
  if (provider === 'bitbucket') return 'bitbucket-pipelines.yml';
  if (provider === 'jenkins') return 'Jenkinsfile';
  if (provider === 'azure') return 'azure-pipelines.yml';
  return '.github/workflows/sharkcraft.yml';
}

export function renderJenkinsCiWorkflow(options: ICiProviderScaffoldOptions = {}): string {
  const bun = options.bunVersion ?? '1.1.0';
  const lines: string[] = [];
  lines.push('// SharkCraft CI scaffold — generated by `shrk ci scaffold jenkins`.');
  lines.push('// Declarative pipeline. Edit by hand if you outgrow the defaults.');
  lines.push('pipeline {');
  lines.push('  agent {');
  lines.push('    docker {');
  lines.push(`      image 'oven/bun:${bun}'`);
  lines.push('      args  \'-u 0\'');
  lines.push('    }');
  lines.push('  }');
  lines.push('  options { timestamps() }');
  lines.push('  stages {');
  lines.push('    stage(\'Install\') {');
  lines.push('      steps {');
  lines.push('        sh \'bun install --frozen-lockfile\'');
  lines.push('        sh \'bun run shrk doctor\'');
  lines.push('      }');
  lines.push('    }');
  if (options.withQuality) {
    lines.push('    stage(\'SharkCraft quality\') {');
    lines.push('      steps {');
    lines.push('        sh \'bun run shrk quality --ci\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withPolicy) {
    lines.push('    stage(\'SharkCraft policy\') {');
    lines.push('      steps {');
    lines.push('        sh \'mkdir -p .sharkcraft/reports\'');
    lines.push('        sh \'bun run shrk policy run --json > .sharkcraft/reports/policy.json\'');
    if (options.withPolicySnapshotGate) {
      lines.push('        sh \'bun run shrk policy snapshot --all --gate --json > .sharkcraft/reports/policy-snapshots.json || true\'');
    }
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withImpact) {
    lines.push('    stage(\'SharkCraft impact\') {');
    lines.push('      steps {');
    lines.push('        sh \'mkdir -p .sharkcraft/reports\'');
    lines.push('        sh \'bun run shrk impact --since origin/main --format json > .sharkcraft/reports/impact.json || true\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withReview) {
    lines.push('    stage(\'SharkCraft review\') {');
    lines.push('      steps {');
    lines.push('        sh \'mkdir -p .sharkcraft/reports\'');
    lines.push('        sh \'bun run shrk review packet --v3 --since origin/main --json > .sharkcraft/reports/review.json || true\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withReportSite) {
    lines.push('    stage(\'SharkCraft report site\') {');
    lines.push('      steps {');
    lines.push('        sh \'bun run shrk report site --output .sharkcraft/reports/site || true\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withBundleReplay) {
    lines.push('    stage(\'SharkCraft bundle replay\') {');
    lines.push('      steps {');
    lines.push('        sh \'bun run shrk bundle replay --all --report --html || true\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withNodeCompat) {
    lines.push('    stage(\'compat:node\') {');
    lines.push('      steps {');
    lines.push('        sh \'bun run compat:node --json > .sharkcraft/reports/compat-node.json || true\'');
    lines.push('      }');
    lines.push('    }');
  }
  if (options.withReleaseReadiness) {
    lines.push('    stage(\'Release readiness gate\') {');
    lines.push('      steps {');
    lines.push('        sh \'bun run shrk release readiness --json > .sharkcraft/reports/release-readiness.json\'');
    lines.push('      }');
    lines.push('    }');
  }
  lines.push('  }');
  lines.push('  post {');
  lines.push('    always {');
  lines.push('      archiveArtifacts artifacts: \'.sharkcraft/reports/**/*\', allowEmptyArchive: true');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  // Trailing comments to ease customization.
  lines.push('');
  lines.push('// Customization notes:');
  lines.push('//   * To install Bun on a self-hosted agent, replace the docker block above with');
  lines.push('//     a shell step that downloads bun from https://bun.sh/install.');
  lines.push('//   * Archived artifacts are under .sharkcraft/reports/. Adjust the post block to');
  lines.push('//     fan out to your artifact server / Slack notifier.');
  lines.push('//   * SharkCraft never writes outside .sharkcraft/ — safe to run on shared agents.');
  return lines.join('\n') + '\n';
}

export function renderAzureCiWorkflow(options: ICiProviderScaffoldOptions = {}): string {
  const bun = options.bunVersion ?? '1.1.0';
  const lines: string[] = [];
  lines.push('# SharkCraft CI scaffold — generated by `shrk ci scaffold azure`.');
  lines.push('# Edit by hand if you outgrow the defaults.');
  lines.push('trigger:');
  lines.push('  branches:');
  lines.push('    include:');
  lines.push('      - main');
  lines.push('pr:');
  lines.push('  branches:');
  lines.push('    include:');
  lines.push('      - main');
  lines.push('');
  lines.push('pool:');
  lines.push('  vmImage: ubuntu-latest');
  lines.push('');
  lines.push('stages:');
  lines.push('  - stage: SharkCraft_Install');
  lines.push('    jobs:');
  lines.push('      - job: Install');
  lines.push('        steps:');
  lines.push(`          - script: curl -fsSL https://bun.sh/install | bash -s "bun-v${bun}"`);
  lines.push('            displayName: Install Bun');
  lines.push('          - script: ~/.bun/bin/bun install --frozen-lockfile');
  lines.push('            displayName: bun install');
  lines.push('          - script: ~/.bun/bin/bun run shrk doctor');
  lines.push('            displayName: SharkCraft doctor');
  if (options.withQuality) {
    lines.push('  - stage: SharkCraft_Quality');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: Quality');
    lines.push('        steps:');
    lines.push('          - script: ~/.bun/bin/bun run shrk quality --ci');
    lines.push('            displayName: shrk quality --ci');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-quality');
    lines.push('            condition: always()');
  }
  if (options.withPolicy) {
    lines.push('  - stage: SharkCraft_Policy');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: Policy');
    lines.push('        steps:');
    lines.push('          - script: |');
    lines.push('              mkdir -p .sharkcraft/reports');
    lines.push('              ~/.bun/bin/bun run shrk policy run --json > .sharkcraft/reports/policy.json');
    if (options.withPolicySnapshotGate) {
      lines.push('              ~/.bun/bin/bun run shrk policy snapshot --all --gate --json > .sharkcraft/reports/policy-snapshots.json || true');
    }
    lines.push('            displayName: shrk policy');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-policy');
    lines.push('            condition: always()');
  }
  if (options.withImpact) {
    lines.push('  - stage: SharkCraft_Impact');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: Impact');
    lines.push('        steps:');
    lines.push('          - script: |');
    lines.push('              mkdir -p .sharkcraft/reports');
    lines.push('              ~/.bun/bin/bun run shrk impact --since origin/main --format json > .sharkcraft/reports/impact.json || true');
    lines.push('            displayName: shrk impact');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-impact');
    lines.push('            condition: always()');
  }
  if (options.withReview) {
    lines.push('  - stage: SharkCraft_Review');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: Review');
    lines.push('        steps:');
    lines.push('          - script: |');
    lines.push('              mkdir -p .sharkcraft/reports');
    lines.push('              ~/.bun/bin/bun run shrk review packet --v3 --since origin/main --json > .sharkcraft/reports/review.json || true');
    lines.push('            displayName: shrk review');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-review');
    lines.push('            condition: always()');
  }
  if (options.withReportSite) {
    lines.push('  - stage: SharkCraft_ReportSite');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: ReportSite');
    lines.push('        steps:');
    lines.push('          - script: ~/.bun/bin/bun run shrk report site --output .sharkcraft/reports/site || true');
    lines.push('            displayName: shrk report site');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/site/');
    lines.push('            artifact: sharkcraft-report-site');
    lines.push('            condition: always()');
  }
  if (options.withBundleReplay) {
    lines.push('  - stage: SharkCraft_BundleReplay');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: BundleReplay');
    lines.push('        steps:');
    lines.push('          - script: ~/.bun/bin/bun run shrk bundle replay --all --report --html || true');
    lines.push('            displayName: shrk bundle replay');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-bundle-replay');
    lines.push('            condition: always()');
  }
  if (options.withNodeCompat) {
    lines.push('  - stage: SharkCraft_CompatNode');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: CompatNode');
    lines.push('        steps:');
    lines.push('          - script: ~/.bun/bin/bun run compat:node --json > .sharkcraft/reports/compat-node.json || true');
    lines.push('            displayName: compat:node');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-compat-node');
    lines.push('            condition: always()');
  }
  if (options.withReleaseReadiness) {
    lines.push('  - stage: SharkCraft_ReleaseReadiness');
    lines.push('    dependsOn: SharkCraft_Install');
    lines.push('    jobs:');
    lines.push('      - job: ReleaseReadiness');
    lines.push('        steps:');
    lines.push('          - script: ~/.bun/bin/bun run shrk release readiness --json > .sharkcraft/reports/release-readiness.json');
    lines.push('            displayName: shrk release readiness');
    lines.push('          - publish: $(System.DefaultWorkingDirectory)/.sharkcraft/reports/');
    lines.push('            artifact: sharkcraft-release-readiness');
    lines.push('            condition: always()');
  }
  // Trailing comments to ease customization.
  lines.push('');
  lines.push('# Customization notes:');
  lines.push('#   * Self-hosted agents may already have Bun installed — drop the install script in that case.');
  lines.push('#   * Adjust artifact retention via your Azure DevOps project settings (default is 30 days).');
  lines.push('#   * SharkCraft writes only to .sharkcraft/ — never modifies source on the agent.');
  return lines.join('\n') + '\n';
}

export function renderBundleReplayWorkflow(
  options: IBundleReplayScaffoldOptions = {},
): string {
  const name = options.name ?? 'SharkCraft bundle replay';
  const bun = options.bunVersion ?? '1.1.0';
  const schedule: BundleReplaySchedule = options.schedule ?? 'weekly';
  const lines: string[] = [];
  lines.push(`# Generated by \`shrk bundle replay scaffold github-actions\`.`);
  lines.push(`name: ${name}`);
  lines.push('on:');
  if (schedule !== 'manual') {
    lines.push('  schedule:');
    lines.push(scheduleCron(schedule));
  }
  lines.push('  workflow_dispatch: {}');
  lines.push('jobs:');
  lines.push('  bundle-replay:');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    timeout-minutes: 15');
  lines.push('    steps:');
  lines.push(setup(bun));
  lines.push("      - name: Replay all bundles");
  lines.push("        run: |");
  lines.push("          mkdir -p .sharkcraft/reports");
  lines.push("          bun run shrk bundle replay --all --report --html || true");
  if (options.withReportSite) {
    lines.push("      - name: Build static report site");
    lines.push("        run: bun run shrk report site --output .sharkcraft/reports/site || true");
  }
  lines.push("      - name: Upload replay artifacts");
  lines.push("        if: always()");
  lines.push("        uses: actions/upload-artifact@v4");
  lines.push("        with:");
  lines.push("          name: bundle-replay-report");
  lines.push("          path: |");
  lines.push("            .sharkcraft/reports/**");
  lines.push("          if-no-files-found: ignore");
  return lines.join('\n') + '\n';
}
