import { mkdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import * as nodePath from 'node:path';
import {
  DemoScenario,
  getDemoScript,
  listDemoScenarios,
  renderDemoScriptShell,
  type IDemoScript,
} from './demo-script.ts';

export const DEMO_PACKAGE_SCHEMA = 'sharkcraft.demo-package/v1';

export type DemoPackageScope = 'all' | DemoScenario;

export interface IDemoPackageFile {
  /** Absolute path on disk. */
  path: string;
  bytes: number;
  /** Short description (shown in README index). */
  description: string;
}

export interface IDemoPackageResult {
  schema: typeof DEMO_PACKAGE_SCHEMA;
  outputDir: string;
  scenarios: readonly DemoScenario[];
  files: readonly IDemoPackageFile[];
}

export interface IBuildDemoPackageInput {
  outputDir: string;
  /** `all` includes every scenario; otherwise just one scenario. */
  scope: DemoPackageScope;
}

function resolveScenarios(scope: DemoPackageScope): DemoScenario[] {
  if (scope === 'all') return [...listDemoScenarios()];
  return [scope];
}

function readme(scenarios: readonly IDemoScript[]): string {
  const lines: string[] = [];
  lines.push('# SharkCraft demo package');
  lines.push('');
  lines.push('Generated by `shrk demo package`. Drop this folder onto another machine,');
  lines.push('read `expected-commands.md`, then run `demo.sh` after reviewing it.');
  lines.push('');
  lines.push('## Scenarios');
  lines.push('');
  for (const s of scenarios) {
    lines.push(`### ${s.scenario}`);
    lines.push('');
    lines.push(s.description);
    lines.push('');
    lines.push(`See \`scenario-${s.scenario}.sh\` for the runnable transcript.`);
    lines.push('');
  }
  lines.push('## Files in this package');
  lines.push('');
  lines.push('- `README.md` — this file');
  lines.push('- `demo.sh` — one-shot script for the included scenarios');
  lines.push('- `expected-commands.md` — what each script will run');
  lines.push('- `sample-output-notes.md` — what to expect from the output');
  for (const s of scenarios) {
    lines.push(`- \`scenario-${s.scenario}.sh\``);
  }
  lines.push('');
  lines.push('## Safety');
  lines.push('');
  lines.push('- No script executes itself. SharkCraft only generates these files.');
  lines.push('- The CLI is the only write path; the MCP server stays read-only.');
  lines.push('- Replace `bun` with your runtime if you are not using Bun.');
  return lines.join('\n') + '\n';
}

function combinedDemoScript(scenarios: readonly IDemoScript[]): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# SharkCraft demo bundle — generated by `shrk demo package`.');
  lines.push('# Each scenario is delegated to its scenario-<name>.sh file so you can');
  lines.push('# run them individually or as a group. Nothing destructive runs here.');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push('cd "$(dirname "$0")"');
  lines.push('');
  for (const s of scenarios) {
    lines.push(`echo "=== scenario: ${s.scenario} ==="`);
    lines.push(`./scenario-${s.scenario}.sh`);
    lines.push('');
  }
  lines.push('echo "All scenarios finished."');
  return lines.join('\n') + '\n';
}

function expectedCommands(scenarios: readonly IDemoScript[]): string {
  const lines: string[] = [];
  lines.push('# Expected commands');
  lines.push('');
  lines.push('This document lists every command the demo scripts run. Inspect it before');
  lines.push('executing `demo.sh` so the recipient knows exactly what to expect.');
  lines.push('');
  for (const s of scenarios) {
    lines.push(`## ${s.scenario} — ${s.title}`);
    lines.push('');
    lines.push(`> ${s.description}`);
    lines.push('');
    let i = 1;
    for (const step of s.steps) {
      lines.push(`${i}. **${step.title}**`);
      for (const c of step.commands) lines.push(`   - \`${c}\``);
      if (step.notes) lines.push(`   - _note: ${step.notes}_`);
      if (step.destructive) lines.push('   - ⚠ destructive — review before running.');
      i += 1;
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

function sampleOutputNotes(scenarios: readonly IDemoScript[]): string {
  const lines: string[] = [];
  lines.push('# Sample output notes');
  lines.push('');
  lines.push('Quick read of what to expect from each scenario.');
  lines.push('');
  for (const s of scenarios) {
    lines.push(`## ${s.scenario}`);
    lines.push('');
    lines.push(`Step count: ${s.steps.length}`);
    lines.push('');
    lines.push('Expected artifacts:');
    for (const step of s.steps) {
      for (const c of step.commands) {
        const match = /--output\s+([^\s]+)|>\s*([^\s]+)|--output-dir\s+([^\s]+)/.exec(c);
        if (match) {
          const target = match[1] ?? match[2] ?? match[3];
          if (target) lines.push(`- \`${target}\``);
        }
      }
    }
    lines.push('');
  }
  lines.push('Nothing here is published or posted to a third party by default — all');
  lines.push('artifacts stay under `.sharkcraft/` or the path you pass.');
  return lines.join('\n') + '\n';
}

function destructiveCheck(scenarios: readonly IDemoScript[]): string[] {
  const issues: string[] = [];
  for (const s of scenarios) {
    for (const step of s.steps) {
      if (step.destructive) {
        issues.push(`scenario ${s.scenario} step "${step.title}" is marked destructive`);
      }
      for (const c of step.commands) {
        if (/\brm\s+-rf\b/.test(c)) {
          issues.push(`scenario ${s.scenario} command contains rm -rf: ${c}`);
        }
      }
    }
  }
  return issues;
}

export const DEMO_PACKAGE_VALIDATE_SCHEMA = 'sharkcraft.demo-package-validate/v1';

export interface IDemoPackageValidateFinding {
  code:
    | 'destructive-command'
    | 'unknown-shrk-command'
    | 'script-not-executable'
    | 'expected-commands-missing'
    | 'demo-sh-missing';
  severity: 'info' | 'warning' | 'error';
  message: string;
  file?: string;
  line?: number;
}

export interface IDemoPackageValidateReport {
  schema: typeof DEMO_PACKAGE_VALIDATE_SCHEMA;
  generatedAt: string;
  outputDir: string;
  scenariosChecked: readonly DemoScenario[];
  commandsFound: readonly string[];
  findings: readonly IDemoPackageValidateFinding[];
  ok: boolean;
}

export interface IValidateDemoPackageInput {
  scope: DemoPackageScope;
  /** Optional list of known catalog commands; unknown commands become findings. */
  knownCommands?: readonly string[];
  /** Pre-existing directory to inspect. If absent, the package is built into a temp dir. */
  outputDir?: string;
}

function makeTempDemoDir(): string {
  return nodePath.join(tmpdir(), `sharkcraft-demo-validate-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`);
}

const DESTRUCTIVE_LINE_RE = [/\brm\s+-rf\b/, /\bdd\s+if=/, /\bmkfs\b/];

function parseExpectedCommands(body: string): string[] {
  const cmds: string[] = [];
  for (const raw of body.split(/\r?\n/)) {
    const m = /-\s+`([^`]+)`/.exec(raw);
    if (m && m[1]?.includes('shrk')) cmds.push(m[1].trim());
  }
  return cmds;
}

export function validateDemoPackage(input: IValidateDemoPackageInput): IDemoPackageValidateReport {
  const ownsDir = !input.outputDir;
  const outputDir = input.outputDir ?? makeTempDemoDir();
  if (ownsDir) {
    buildDemoPackage({ outputDir, scope: input.scope });
  }
  const findings: IDemoPackageValidateFinding[] = [];
  const expectedFile = nodePath.join(outputDir, 'expected-commands.md');
  const demoSh = nodePath.join(outputDir, 'demo.sh');
  let body = '';
  try {
    body = readFileSync(expectedFile, 'utf8');
  } catch {
    findings.push({
      code: 'expected-commands-missing',
      severity: 'error',
      message: `Missing expected-commands.md in ${outputDir}`,
      file: expectedFile,
    });
  }
  const commands = body ? parseExpectedCommands(body) : [];
  if (input.knownCommands && input.knownCommands.length > 0) {
    for (const cmd of commands) {
      let known = false;
      for (const k of input.knownCommands) {
        if (k === cmd || k.startsWith(cmd) || cmd.startsWith(k)) {
          known = true;
          break;
        }
      }
      if (!known) {
        findings.push({
          code: 'unknown-shrk-command',
          severity: 'warning',
          message: `expected-commands.md references "${cmd}" which is not in the command catalog.`,
          file: expectedFile,
        });
      }
    }
  }
  // Scan each scenario shell + demo.sh for destructive commands.
  const scenarios = resolveScenarios(input.scope);
  for (const s of scenarios) {
    const file = nodePath.join(outputDir, `scenario-${s}.sh`);
    let stat;
    try {
      stat = statSync(file);
    } catch {
      continue;
    }
    if ((stat.mode & 0o111) === 0) {
      findings.push({
        code: 'script-not-executable',
        severity: 'warning',
        message: `scenario-${s}.sh is not executable.`,
        file,
      });
    }
    let scriptBody = '';
    try {
      scriptBody = readFileSync(file, 'utf8');
    } catch {
      continue;
    }
    const lines = scriptBody.split(/\r?\n/);
    for (let i = 0; i < lines.length; i += 1) {
      for (const re of DESTRUCTIVE_LINE_RE) {
        if (re.test(lines[i]!)) {
          findings.push({
            code: 'destructive-command',
            severity: 'error',
            message: `scenario-${s}.sh contains a destructive command on line ${i + 1}.`,
            file,
            line: i + 1,
          });
        }
      }
    }
  }
  try {
    const stat = statSync(demoSh);
    if ((stat.mode & 0o111) === 0) {
      findings.push({
        code: 'script-not-executable',
        severity: 'warning',
        message: 'demo.sh is not executable.',
        file: demoSh,
      });
    }
  } catch {
    findings.push({
      code: 'demo-sh-missing',
      severity: 'error',
      message: 'demo.sh missing from generated package.',
      file: demoSh,
    });
  }
  const ok = findings.filter((f) => f.severity === 'error').length === 0;
  return {
    schema: DEMO_PACKAGE_VALIDATE_SCHEMA,
    generatedAt: new Date().toISOString(),
    outputDir,
    scenariosChecked: scenarios,
    commandsFound: commands,
    findings,
    ok,
  };
}

export function renderDemoPackageValidateText(report: IDemoPackageValidateReport): string {
  const lines: string[] = [];
  lines.push('# Demo package validation');
  lines.push(`OK: ${report.ok ? 'yes' : 'no'}  · scenarios: ${report.scenariosChecked.join(', ')}`);
  lines.push(`Commands referenced: ${report.commandsFound.length}`);
  if (report.findings.length === 0) {
    lines.push('No findings.');
  } else {
    lines.push('Findings:');
    for (const f of report.findings) {
      const loc = f.file ? ` (${f.file}${f.line ? `:${f.line}` : ''})` : '';
      lines.push(`  [${f.severity}] ${f.code}: ${f.message}${loc}`);
    }
  }
  return lines.join('\n') + '\n';
}

export function buildDemoPackage(input: IBuildDemoPackageInput): IDemoPackageResult {
  const scenarios = resolveScenarios(input.scope);
  const scripts = scenarios.map((s) => getDemoScript(s));
  // Safety check: refuse to emit anything if a destructive marker is found.
  const dangerous = destructiveCheck(scripts);
  if (dangerous.length > 0) {
    throw new Error(
      `Demo package refused — destructive content detected:\n${dangerous.join('\n')}`,
    );
  }
  mkdirSync(input.outputDir, { recursive: true });
  const files: IDemoPackageFile[] = [];
  const write = (name: string, body: string, description: string, mode?: number): void => {
    const full = nodePath.join(input.outputDir, name);
    writeFileSync(full, body, mode ? { mode } : 'utf8');
    files.push({ path: full, bytes: Buffer.byteLength(body, 'utf8'), description });
  };
  write('README.md', readme(scripts), 'Demo package overview');
  write('expected-commands.md', expectedCommands(scripts), 'List of every command each scenario will run');
  write('sample-output-notes.md', sampleOutputNotes(scripts), 'What to expect from each scenario');
  for (const s of scripts) {
    write(`scenario-${s.scenario}.sh`, renderDemoScriptShell(s), s.title, 0o755);
  }
  write('demo.sh', combinedDemoScript(scripts), 'One-shot driver for the included scenarios', 0o755);
  return {
    schema: DEMO_PACKAGE_SCHEMA,
    outputDir: nodePath.resolve(input.outputDir),
    scenarios: scripts.map((s) => s.scenario),
    files,
  };
}
