/**
 * Demo-workflow generator. Renders ready-to-run CI workflow files that exercise
 * SharkCraft's PR-review surface (impact + review packet + report site). The
 * generator never executes anything and never makes external network calls.
 * Workflows it emits never publish or post to PRs unless the human explicitly
 * uncomments the optional steps.
 */

export const DEMO_WORKFLOW_SCHEMA = 'sharkcraft.demo-workflow/v1';

export type DemoWorkflowKind = 'pr-review';

export type DemoWorkflowProvider = 'github-actions' | 'gitlab' | 'bitbucket';

export interface IDemoWorkflowOptions {
  bunVersion?: string;
  /** Reserved — currently only `pr-review` is supported. */
  kind?: DemoWorkflowKind;
}

export interface IDemoWorkflow {
  schema: typeof DEMO_WORKFLOW_SCHEMA;
  kind: DemoWorkflowKind;
  provider: DemoWorkflowProvider;
  /** Suggested workflow file path. */
  defaultOutputPath: string;
  body: string;
  /** Short summary of what the workflow does. */
  notes: readonly string[];
}

function ghaPrReview(bun: string): string {
  const lines: string[] = [];
  lines.push('# SharkCraft demo PR review workflow.');
  lines.push('# Generated by `shrk demo workflow pr-review --provider github-actions`.');
  lines.push('# - runs the read-only review surface on every PR.');
  lines.push('# - no publishing, no posting comments by default.');
  lines.push('# - uncomment the optional `gh pr comment` step to opt into PR comment posting.');
  lines.push('name: SharkCraft PR review (demo)');
  lines.push('on:');
  lines.push('  pull_request:');
  lines.push('    branches: [main]');
  lines.push('jobs:');
  lines.push('  sharkcraft-review:');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    timeout-minutes: 15');
  lines.push('    permissions:');
  lines.push('      contents: read');
  lines.push('      # pull-requests: write   # only needed if you uncomment the gh pr comment step');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('        with:');
  lines.push('          fetch-depth: 0');
  lines.push('      - uses: oven-sh/setup-bun@v1');
  lines.push(`        with: { bun-version: '${bun}' }`);
  lines.push('      - run: bun install --frozen-lockfile');
  lines.push('      - name: SharkCraft doctor');
  lines.push('        run: bun run shrk doctor');
  lines.push('      - name: Build review packet (v3)');
  lines.push('        run: |');
  lines.push('          mkdir -p .sharkcraft/reports');
  lines.push('          bun run shrk review packet --v3 --since origin/main --json > .sharkcraft/reports/review.json');
  lines.push('      - name: Compute impact since origin/main');
  lines.push('        run: |');
  lines.push('          bun run shrk impact --since origin/main --format json > .sharkcraft/reports/impact.json');
  lines.push('          bun run shrk impact --since origin/main --format html --output .sharkcraft/reports/impact.html');
  lines.push('      - name: Build static report site');
  lines.push('        run: |');
  lines.push('          bun run shrk report site \\');
  lines.push('            --review .sharkcraft/reports/review.json \\');
  lines.push('            --impact .sharkcraft/reports/impact.json \\');
  lines.push('            --with-impact-graphs \\');
  lines.push('            --output .sharkcraft/reports/site');
  lines.push('      - name: Render PR comment (markdown)');
  lines.push('        run: |');
  lines.push('          bun run shrk review render-comment .sharkcraft/reports/review.json \\');
  lines.push('            --output .sharkcraft/reports/review-comment.md');
  lines.push('      # OPTIONAL: post the comment to the PR (requires permissions.pull-requests: write).');
  lines.push('      # - name: Post review comment to PR');
  lines.push('      #   env:');
  lines.push('      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}');
  lines.push('      #   run: gh pr comment "${{ github.event.pull_request.number }}" --body-file .sharkcraft/reports/review-comment.md');
  lines.push('      - name: Upload SharkCraft reports');
  lines.push('        if: always()');
  lines.push('        uses: actions/upload-artifact@v4');
  lines.push('        with:');
  lines.push('          name: sharkcraft-reports');
  lines.push('          path: |');
  lines.push('            .sharkcraft/reports/**');
  lines.push('          if-no-files-found: ignore');
  return lines.join('\n') + '\n';
}

function gitlabPrReview(bun: string): string {
  const lines: string[] = [];
  lines.push('# SharkCraft demo PR review pipeline.');
  lines.push('# Generated by `shrk demo workflow pr-review --provider gitlab`.');
  lines.push('# - runs the read-only review surface on every MR.');
  lines.push('# - no publishing, no posting comments by default.');
  lines.push('');
  lines.push('stages:');
  lines.push('  - sharkcraft_review');
  lines.push('');
  lines.push('sharkcraft:pr-review:');
  lines.push('  stage: sharkcraft_review');
  lines.push(`  image: oven/bun:${bun}`);
  lines.push('  rules:');
  lines.push('    - if: $CI_PIPELINE_SOURCE == "merge_request_event"');
  lines.push('  variables:');
  lines.push('    GIT_DEPTH: "0"');
  lines.push('  script:');
  lines.push('    - bun install --frozen-lockfile');
  lines.push('    - mkdir -p .sharkcraft/reports');
  lines.push('    - bun run shrk doctor');
  lines.push('    - bun run shrk review packet --v3 --since $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --json > .sharkcraft/reports/review.json');
  lines.push('    - bun run shrk impact --since $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --format json > .sharkcraft/reports/impact.json');
  lines.push('    - bun run shrk impact --since $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --format html --output .sharkcraft/reports/impact.html');
  lines.push('    - bun run shrk report site --review .sharkcraft/reports/review.json --impact .sharkcraft/reports/impact.json --with-impact-graphs --output .sharkcraft/reports/site');
  lines.push('    - bun run shrk review render-comment .sharkcraft/reports/review.json --output .sharkcraft/reports/review-comment.md');
  lines.push('  artifacts:');
  lines.push('    when: always');
  lines.push('    paths:');
  lines.push('      - .sharkcraft/reports/');
  lines.push('    expire_in: 1 week');
  lines.push('');
  lines.push('# OPTIONAL: post the comment to the MR.');
  lines.push('# Requires CI_JOB_TOKEN read access + python; commented out by default.');
  lines.push('# sharkcraft:pr-comment:');
  lines.push('#   stage: sharkcraft_review');
  lines.push('#   needs: ["sharkcraft:pr-review"]');
  lines.push('#   image: curlimages/curl');
  lines.push('#   rules:');
  lines.push('#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"');
  lines.push('#   script:');
  lines.push('#     - "curl --request POST --header \\"PRIVATE-TOKEN: $REVIEW_TOKEN\\" --form body=@.sharkcraft/reports/review-comment.md $CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"');
  return lines.join('\n') + '\n';
}

function bitbucketPrReview(bun: string): string {
  const lines: string[] = [];
  lines.push('# SharkCraft demo PR review pipeline.');
  lines.push('# Generated by `shrk demo workflow pr-review --provider bitbucket`.');
  lines.push('# - runs the read-only review surface on every pull request.');
  lines.push('# - no publishing, no posting comments by default.');
  lines.push('');
  lines.push(`image: oven/bun:${bun}`);
  lines.push('');
  lines.push('pipelines:');
  lines.push('  pull-requests:');
  lines.push('    "**":');
  lines.push('      - step:');
  lines.push('          name: SharkCraft PR review (demo)');
  lines.push('          script:');
  lines.push('            - bun install --frozen-lockfile');
  lines.push('            - mkdir -p .sharkcraft/reports');
  lines.push('            - bun run shrk doctor');
  lines.push('            - bun run shrk review packet --v3 --since origin/$BITBUCKET_PR_DESTINATION_BRANCH --json > .sharkcraft/reports/review.json');
  lines.push('            - bun run shrk impact --since origin/$BITBUCKET_PR_DESTINATION_BRANCH --format json > .sharkcraft/reports/impact.json');
  lines.push('            - bun run shrk impact --since origin/$BITBUCKET_PR_DESTINATION_BRANCH --format html --output .sharkcraft/reports/impact.html');
  lines.push('            - bun run shrk report site --review .sharkcraft/reports/review.json --impact .sharkcraft/reports/impact.json --with-impact-graphs --output .sharkcraft/reports/site');
  lines.push('            - bun run shrk review render-comment .sharkcraft/reports/review.json --output .sharkcraft/reports/review-comment.md');
  lines.push('          artifacts:');
  lines.push('            - .sharkcraft/reports/**');
  lines.push('');
  lines.push('# OPTIONAL: post the comment to the PR using the Bitbucket REST API.');
  lines.push('# Commented out by default; configure $BITBUCKET_TOKEN before enabling.');
  return lines.join('\n') + '\n';
}

const NOTES = [
  'Runs the read-only SharkCraft review surface — impact, review packet, report site.',
  'Never publishes or posts to a PR by default. Optional comment-posting steps are commented out.',
  'Uploads all generated artifacts so reviewers can download them from the CI run.',
];

export function defaultDemoWorkflowOutputPath(
  provider: DemoWorkflowProvider,
  kind: DemoWorkflowKind = 'pr-review',
): string {
  if (provider === 'github-actions')
    return `.github/workflows/sharkcraft-${kind}.yml`;
  if (provider === 'gitlab') return `.gitlab/${kind}-pipeline.yml`;
  if (provider === 'bitbucket') return `bitbucket-pipelines.${kind}.yml`;
  return `sharkcraft-${kind}.yml`;
}

export function renderDemoWorkflow(
  provider: DemoWorkflowProvider,
  options: IDemoWorkflowOptions = {},
): IDemoWorkflow {
  const bun = options.bunVersion ?? '1.1.0';
  const kind: DemoWorkflowKind = options.kind ?? 'pr-review';
  let body: string;
  if (provider === 'github-actions') body = ghaPrReview(bun);
  else if (provider === 'gitlab') body = gitlabPrReview(bun);
  else if (provider === 'bitbucket') body = bitbucketPrReview(bun);
  else throw new Error(`Unknown provider: ${provider}`);
  return {
    schema: DEMO_WORKFLOW_SCHEMA,
    kind,
    provider,
    defaultOutputPath: defaultDemoWorkflowOutputPath(provider, kind),
    body,
    notes: NOTES,
  };
}
