import { buildImpactTree } from './impact-render.ts';
import type { IImpactAnalysis } from './impact-analysis.ts';

export const IMPACT_GRAPH_SCHEMA = 'sharkcraft.impact-graph/v1';

export type ImpactGraphFormat = 'mermaid' | 'dot';

export interface IImpactGraphOptions {
  /** Max nodes per branch. */
  width?: number;
  /** Max depth of the tree. */
  depth?: number;
  /** Optional fallback label for the root when the impact has no targets. */
  rootLabel?: string;
}

function escMermaidLabel(s: string): string {
  // Mermaid label chars to escape — wrap in quotes for special chars.
  return s.replace(/"/g, '\\"');
}

function escDot(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function safeId(s: string, used: Map<string, string>): string {
  const existing = used.get(s);
  if (existing) return existing;
  const slug = `n${used.size}`;
  used.set(s, slug);
  return slug;
}

function riskClassFor(risk: string): string {
  switch (risk) {
    case 'critical':
      return 'risk-critical';
    case 'high':
    case 'medium':
      return 'risk-warn';
    default:
      return 'risk-ok';
  }
}

/** Build a Mermaid flowchart for an impact analysis dependency tree. */
export function renderImpactMermaid(
  impact: IImpactAnalysis,
  options: IImpactGraphOptions = {},
): string {
  const treeOpts: { width?: number; depth?: number } = {};
  if (options.width !== undefined) treeOpts.width = options.width;
  if (options.depth !== undefined) treeOpts.depth = options.depth;
  const tree = buildImpactTree(impact, treeOpts);
  const ids = new Map<string, string>();
  const lines: string[] = [];
  lines.push('%% Generated by SharkCraft impact-analysis/v2 — Mermaid flowchart.');
  lines.push('flowchart LR');
  lines.push('  classDef risk-critical fill:#ffebe9,stroke:#cf222e,color:#cf222e');
  lines.push('  classDef risk-warn fill:#fff8c5,stroke:#9a6700,color:#9a6700');
  lines.push('  classDef risk-ok fill:#dafbe1,stroke:#1a7f37,color:#1a7f37');
  lines.push('  classDef truncated stroke-dasharray: 4 2,color:#57606a');

  if (tree.length === 0) {
    const rootId = safeId('__root__', ids);
    const label = options.rootLabel ?? impact.task ?? '(no targets)';
    lines.push(`  ${rootId}["${escMermaidLabel(label)}"]`);
    lines.push(`  class ${rootId} ${riskClassFor(impact.risk)};`);
    return lines.join('\n') + '\n';
  }

  const visit = (node: { file: string; children: readonly { file: string; children: readonly unknown[] }[] }, depth: number): void => {
    const id = safeId(node.file, ids);
    lines.push(`  ${id}["${escMermaidLabel(node.file)}"]`);
    if (depth === 0) {
      lines.push(`  class ${id} ${riskClassFor(impact.risk)};`);
    }
    for (const child of node.children) {
      const childId = safeId(child.file, ids);
      lines.push(`  ${id} --> ${childId}`);
      visit(child as { file: string; children: readonly { file: string; children: readonly unknown[] }[] }, depth + 1);
    }
  };
  for (const root of tree) visit(root as never, 0);

  // Truncation note when the analysis flagged truncated transitive list.
  const truncated = impact.truncations.find((t) => t.list === 'transitiveDependents');
  if (truncated) {
    const noteId = safeId('__truncated__', ids);
    lines.push(`  ${noteId}["… ${truncated.total - truncated.shown} more dependents omitted"]`);
    lines.push(`  class ${noteId} truncated;`);
  }
  return lines.join('\n') + '\n';
}

/** Build a DOT graph for the dependency tree (use with graphviz). */
export function renderImpactDot(
  impact: IImpactAnalysis,
  options: IImpactGraphOptions = {},
): string {
  const treeOpts: { width?: number; depth?: number } = {};
  if (options.width !== undefined) treeOpts.width = options.width;
  if (options.depth !== undefined) treeOpts.depth = options.depth;
  const tree = buildImpactTree(impact, treeOpts);
  const ids = new Map<string, string>();
  const lines: string[] = [];
  lines.push('// Generated by SharkCraft impact-analysis/v2 — Graphviz DOT.');
  lines.push('digraph ImpactTree {');
  lines.push('  rankdir=LR;');
  lines.push('  node [shape=box, style="rounded,filled", fontname="Helvetica"];');
  const rootColor =
    impact.risk === 'critical' ? '#ffebe9' : impact.risk === 'high' || impact.risk === 'medium' ? '#fff8c5' : '#dafbe1';

  if (tree.length === 0) {
    const id = safeId('__root__', ids);
    const label = options.rootLabel ?? impact.task ?? '(no targets)';
    lines.push(`  ${id} [label="${escDot(label)}", fillcolor="${rootColor}"];`);
    lines.push('}');
    return lines.join('\n') + '\n';
  }

  const visit = (node: { file: string; children: readonly { file: string; children: readonly unknown[] }[] }, depth: number): void => {
    const id = safeId(node.file, ids);
    const fill = depth === 0 ? rootColor : '#ffffff';
    lines.push(`  ${id} [label="${escDot(node.file)}", fillcolor="${fill}"];`);
    for (const child of node.children) {
      const childId = safeId(child.file, ids);
      lines.push(`  ${id} -> ${childId};`);
      visit(child as never, depth + 1);
    }
  };
  for (const root of tree) visit(root as never, 0);

  const truncated = impact.truncations.find((t) => t.list === 'transitiveDependents');
  if (truncated) {
    const noteId = safeId('__truncated__', ids);
    lines.push(
      `  ${noteId} [label="… ${truncated.total - truncated.shown} more dependents omitted", style="dashed,filled", fillcolor="#f6f8fa"];`,
    );
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

export function renderImpactGraph(
  impact: IImpactAnalysis,
  format: ImpactGraphFormat,
  options: IImpactGraphOptions = {},
): string {
  return format === 'dot' ? renderImpactDot(impact, options) : renderImpactMermaid(impact, options);
}
