import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import * as nodePath from 'node:path';
import type { IOnboardingPlan, IInferredTemplateCandidate } from './onboarding.ts';
import { renderOnboardingReport } from './onboarding-report.ts';
import type { IImportedAgentRulesBundle } from './onboarding-agent-import.ts';

export interface IWrittenDraft {
  path: string;
  bytes: number;
}

export interface IWriteOnboardingDraftsOptions {
  projectRoot: string;
  /** Override the output directory. Default: `<projectRoot>/sharkcraft/onboarding`. */
  outDir?: string;
  /**
   * When provided, write an additional `imported-agent-rules.draft.ts` file
   * containing the entries parsed from AGENTS.md / CLAUDE.md / .cursor/rules.
   * The file is still under the onboarding/ subdir — never written to rules.ts.
   */
  importedAgentRules?: IImportedAgentRulesBundle;
}

export interface IWriteOnboardingDraftsResult {
  outDir: string;
  files: IWrittenDraft[];
}

/**
 * Write onboarding drafts under sharkcraft/onboarding/. This function NEVER
 * writes outside that subdirectory (the caller can override the location, but
 * the function refuses any path that escapes the resolved outDir).
 */
export function writeOnboardingDrafts(
  plan: IOnboardingPlan,
  options: IWriteOnboardingDraftsOptions,
): IWriteOnboardingDraftsResult {
  const outDir = nodePath.resolve(
    options.outDir ??
      nodePath.join(options.projectRoot, 'sharkcraft', 'onboarding'),
  );
  ensureDir(outDir);
  const files: IWrittenDraft[] = [];
  const write = (name: string, body: string): void => {
    const full = nodePath.join(outDir, name);
    // Belt-and-braces: refuse anything that escapes outDir.
    if (!full.startsWith(outDir + nodePath.sep)) {
      throw new Error(`draft path escapes outDir: ${name}`);
    }
    writeFileSync(full, body, 'utf8');
    files.push({ path: full, bytes: Buffer.byteLength(body, 'utf8') });
  };

  write('onboarding-report.md', renderOnboardingReport(plan));
  write('inferred-rules.draft.ts', renderInferredRulesDraft(plan));
  write('inferred-paths.draft.ts', renderInferredPathsDraft(plan));
  write('inferred-templates.draft.ts', renderInferredTemplatesDraft(plan));
  write('inferred-boundaries.draft.ts', renderInferredBoundariesDraft(plan));
  write('inferred-pipelines.draft.ts', renderInferredPipelinesDraft(plan));
  if (options.importedAgentRules && options.importedAgentRules.entries.length > 0) {
    write(
      'imported-agent-rules.draft.ts',
      renderImportedAgentRulesDraft(options.importedAgentRules),
    );
  }

  return { outDir, files };
}

// ─── Renderers ───────────────────────────────────────────────────────────────

function renderInferredRulesDraft(plan: IOnboardingPlan): string {
  const lines: string[] = [];
  lines.push(
    `// Inferred rules draft — generated by \`shrk onboard\`. Review before adopting.`,
  );
  lines.push(`// Move keepers into sharkcraft/rules.ts.`);
  lines.push(`export default [`);
  for (const r of plan.inferredRules) {
    lines.push(`  {`);
    lines.push(`    id: ${literal(r.id)},`);
    lines.push(`    type: 'rule',`);
    lines.push(`    title: ${literal(r.title)},`);
    lines.push(`    priority: ${literal(r.priority)},`);
    lines.push(`    content: ${literal(r.content)},`);
    lines.push(`    tags: ${literal(['inferred', r.source])},`);
    lines.push(`    // reason: ${escapeSingleLineComment(r.reason)}`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  return lines.join('\n') + '\n';
}

function renderInferredPathsDraft(plan: IOnboardingPlan): string {
  const lines: string[] = [];
  lines.push(
    `// Inferred path conventions draft — generated by \`shrk onboard\`. Review before adopting.`,
  );
  lines.push(`// Move keepers into sharkcraft/paths.ts.`);
  lines.push(`export default [`);
  for (const p of plan.inferredPathConventions) {
    lines.push(`  {`);
    lines.push(`    id: ${literal(p.id)},`);
    lines.push(`    type: 'path',`);
    lines.push(`    title: ${literal(p.title)},`);
    lines.push(`    content: ${literal(p.content)},`);
    lines.push(`    patterns: ${literal(p.patterns)},`);
    lines.push(`    tags: ${literal(['inferred', 'path'])},`);
    lines.push(`    // reason: ${escapeSingleLineComment(p.reason)}`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  return lines.join('\n') + '\n';
}

function renderInferredTemplatesDraft(plan: IOnboardingPlan): string {
  const lines: string[] = [];
  const anyScaffolded = plan.inferredTemplateCandidates.some((t) => t.scaffold);
  lines.push(
    `// Inferred template candidates — generated by \`shrk onboard\`.`,
  );
  if (anyScaffolded) {
    lines.push(
      `// Entries with \`runnable: true\` ship a draft body with placeholder variables.`,
    );
    lines.push(
      `// Review carefully (especially low-confidence entries) before moving to sharkcraft/templates.ts.`,
    );
  } else {
    lines.push(
      `// NOT runnable until you fill in targetPath + content. Re-run with \`--scaffold-templates\` to draft bodies.`,
    );
  }
  lines.push(`export default [`);
  for (const t of plan.inferredTemplateCandidates) {
    renderTemplateCandidate(lines, t);
  }
  lines.push(`];`);
  return lines.join('\n') + '\n';
}

function renderTemplateCandidate(
  lines: string[],
  t: IInferredTemplateCandidate,
): void {
  lines.push(`  {`);
  lines.push(`    id: ${literal(t.id)},`);
  lines.push(`    name: ${literal(t.name)},`);
  lines.push(`    description: ${literal(t.description)},`);
  lines.push(`    confidence: ${literal(t.confidence)},`);
  if (t.targetPathHint) {
    lines.push(`    // targetPath hint: ${escapeSingleLineComment(t.targetPathHint)}`);
  }
  if (t.sample) {
    lines.push(`    // sample: ${escapeSingleLineComment(t.sample)}`);
  }
  lines.push(`    // reason: ${escapeSingleLineComment(t.reason)}`);
  if (t.scaffold) {
    lines.push(`    runnable: true,`);
    lines.push(`    scaffold: {`);
    lines.push(`      id: ${literal(t.scaffold.id)},`);
    lines.push(`      name: ${literal(t.scaffold.name)},`);
    lines.push(`      description: ${literal(t.scaffold.description)},`);
    lines.push(`      targetPath: ${literal(t.scaffold.targetPath)},`);
    lines.push(`      variables: [`);
    for (const v of t.scaffold.variables) {
      lines.push(`        {`);
      lines.push(`          name: ${literal(v.name)},`);
      lines.push(`          description: ${literal(v.description)},`);
      if (typeof v.default === 'string') {
        lines.push(`          default: ${literal(v.default)},`);
      }
      lines.push(`        },`);
    }
    lines.push(`      ],`);
    lines.push(`      content: ${renderMultilineTemplateLiteral(t.scaffold.content)},`);
    if (t.scaffold.warnings.length > 0) {
      lines.push(`      // warnings:`);
      for (const w of t.scaffold.warnings) {
        lines.push(`      //   - ${escapeSingleLineComment(w)}`);
      }
    }
    lines.push(`    },`);
  }
  lines.push(`  },`);
}

function renderMultilineTemplateLiteral(content: string): string {
  // Use a tagged template literal-safe form. Backticks and ${ must be escaped.
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return '`' + escaped + '`';
}

function renderInferredBoundariesDraft(plan: IOnboardingPlan): string {
  const lines: string[] = [];
  lines.push(
    `// Inferred boundary rules draft — generated by \`shrk onboard\`. Review before adopting.`,
  );
  lines.push(
    `// Drop into sharkcraft/boundaries.ts (and register via sharkcraft.config.ts boundaryFiles).`,
  );
  lines.push(`export default [`);
  for (const b of plan.inferredBoundaryRules) {
    lines.push(`  {`);
    lines.push(`    id: ${literal(b.id)},`);
    lines.push(`    title: ${literal(b.title)},`);
    lines.push(`    severity: ${literal(b.severity)},`);
    lines.push(`    from: ${literal(b.from)},`);
    if (b.forbiddenImports) {
      lines.push(`    forbiddenImports: ${literal(b.forbiddenImports)},`);
    }
    if (b.allowedImports) {
      lines.push(`    allowedImports: ${literal(b.allowedImports)},`);
    }
    lines.push(`    suggestedFix: ${literal(b.suggestedFix)},`);
    lines.push(`    // reason: ${escapeSingleLineComment(b.reason)}`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  return lines.join('\n') + '\n';
}

function renderInferredPipelinesDraft(plan: IOnboardingPlan): string {
  const lines: string[] = [];
  lines.push(
    `// Inferred pipelines draft — generated by \`shrk onboard\`. Review before adopting.`,
  );
  lines.push(`// Move keepers into sharkcraft/pipelines.ts.`);
  lines.push(`export default [`);
  for (const p of plan.inferredPipelines) {
    lines.push(`  {`);
    lines.push(`    id: ${literal(p.id)},`);
    lines.push(`    title: ${literal(p.title)},`);
    lines.push(`    description: ${literal(p.description)},`);
    lines.push(`    steps: ${renderSteps(p.steps)},`);
    lines.push(`    // reason: ${escapeSingleLineComment(p.reason)}`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  return lines.join('\n') + '\n';
}

function renderSteps(steps: readonly string[]): string {
  const items = steps.map(
    (id) => `      { id: ${literal(id)}, title: ${literal(id)} }`,
  );
  return `[\n${items.join(',\n')}\n    ]`;
}

// ─── Util ────────────────────────────────────────────────────────────────────

function literal(v: unknown): string {
  if (Array.isArray(v)) {
    return `[${v.map((x) => literal(x)).join(', ')}]`;
  }
  if (typeof v === 'string') {
    // Use JSON.stringify for safe escaping.
    return JSON.stringify(v);
  }
  return JSON.stringify(v);
}

function escapeSingleLineComment(s: string): string {
  return s.replace(/\r?\n/g, ' ').replace(/\*\//g, '*​/');
}

function ensureDir(dir: string): void {
  if (existsSync(dir)) return;
  mkdirSync(dir, { recursive: true });
}

function renderImportedAgentRulesDraft(bundle: IImportedAgentRulesBundle): string {
  const lines: string[] = [];
  lines.push(
    `// Imported agent rules draft — generated by \`shrk onboard --import-agents\`.`,
  );
  lines.push(
    `// Source files: ${bundle.sourceFiles.map((s) => escapeSingleLineComment(s)).join(', ') || '(none)'}`,
  );
  lines.push(
    `// Review before adopting; entries flagged "ambiguous" may need a manual rewrite.`,
  );
  lines.push(`export default [`);
  for (const e of bundle.entries) {
    lines.push(`  {`);
    lines.push(`    id: ${literal(e.id)},`);
    lines.push(`    type: ${literal(e.type)},`);
    lines.push(`    title: ${literal(e.title)},`);
    lines.push(`    content: ${literal(e.content)},`);
    lines.push(`    tags: ${literal(e.tags)},`);
    if (e.scope?.length) lines.push(`    scope: ${literal(e.scope)},`);
    if (e.source?.origin) {
      lines.push(`    // origin: ${escapeSingleLineComment(e.source.origin)}`);
    }
    if (e.flaggedAmbiguous) {
      lines.push(`    // ambiguous: please review the wording before adopting`);
    }
    lines.push(`  },`);
  }
  lines.push(`];`);
  if (bundle.warnings.length > 0) {
    lines.push('');
    lines.push('// Warnings:');
    for (const w of bundle.warnings) {
      lines.push(`//   - ${escapeSingleLineComment(w)}`);
    }
  }
  return lines.join('\n') + '\n';
}
