import type { IPlaybook } from './playbook-registry.ts';
import type { ISharkcraftInspection } from './sharkcraft-inspector.ts';

export const PLAYBOOK_SCRIPT_SCHEMA = 'sharkcraft.playbook-script/v1';
export const PLAYBOOK_VALIDATION_SCHEMA = 'sharkcraft.playbook-validation/v1';

export interface IPlaybookScriptInput {
  /** Optional task description to render in the script header. */
  task?: string;
}

export interface IPlaybookScript {
  schema: typeof PLAYBOOK_SCRIPT_SCHEMA;
  playbookId: string;
  title: string;
  task: string | null;
  /** Bash-like preview. */
  script: string;
  /** Step ids → commands actually rendered. */
  steps: readonly { id: string; title: string; humanReview: boolean; commands: readonly string[] }[];
  /** Aggregated verification commands collected across steps. */
  verificationCommands: readonly string[];
}

export interface IPlaybookValidationIssue {
  severity: 'info' | 'warning' | 'error';
  code: string;
  message: string;
  stepId?: string;
}

export interface IPlaybookValidation {
  schema: typeof PLAYBOOK_VALIDATION_SCHEMA;
  playbookId: string;
  issues: readonly IPlaybookValidationIssue[];
  passed: boolean;
}

export function buildPlaybookScript(
  playbook: IPlaybook,
  input: IPlaybookScriptInput = {},
): IPlaybookScript {
  const lines: string[] = [];
  const verification = new Set<string>();
  const steps: { id: string; title: string; humanReview: boolean; commands: readonly string[] }[] = [];

  lines.push('#!/usr/bin/env bash');
  lines.push('# Playbook script preview — generated by `shrk playbooks script`.');
  lines.push('# This script is NEVER executed by SharkCraft. Review and run manually.');
  lines.push('# set -euo pipefail is intentionally omitted; uncomment if you want to run it.');
  lines.push(`# playbook: ${playbook.id}`);
  if (input.task) lines.push(`# task:     ${input.task}`);
  lines.push('');
  lines.push(`echo "Playbook: ${playbook.title.replace(/"/g, '\\"')}"`);
  if (playbook.description) lines.push(`echo "${playbook.description.replace(/"/g, '\\"')}"`);
  lines.push('');
  for (const step of playbook.steps) {
    lines.push(`# === step ${step.id} — ${step.title} ===`);
    if (step.description) lines.push(`#   ${step.description}`);
    if (step.humanReview) {
      lines.push('# ⚠ HUMAN REVIEW REQUIRED before running the commands below.');
    }
    for (const tool of step.mcpTools ?? []) {
      lines.push(`# MCP tool suggestion: ${tool}`);
    }
    const cmds = step.commands ?? [];
    if (cmds.length === 0) {
      lines.push(`# (no commands; manual step)`);
    } else {
      for (const c of cmds) {
        lines.push(c);
      }
    }
    if (step.safetyNotes?.length) {
      for (const n of step.safetyNotes) lines.push(`# safety: ${n}`);
    }
    if (step.verificationCommands?.length) {
      lines.push('# verify:');
      for (const v of step.verificationCommands) {
        lines.push(`#   $ ${v}`);
        verification.add(v);
      }
    }
    lines.push('');
    steps.push({
      id: step.id,
      title: step.title,
      humanReview: Boolean(step.humanReview),
      commands: cmds,
    });
  }
  lines.push('echo "Playbook complete. Run any verification commands listed above."');
  return {
    schema: PLAYBOOK_SCRIPT_SCHEMA,
    playbookId: playbook.id,
    title: playbook.title,
    task: input.task ?? null,
    script: lines.join('\n') + '\n',
    steps,
    verificationCommands: [...verification],
  };
}

export interface IPlaybookPreview {
  playbookId: string;
  title: string;
  description: string | null;
  steps: readonly {
    id: string;
    title: string;
    description?: string;
    commands: readonly string[];
    mcpTools: readonly string[];
    humanReview: boolean;
    verificationCommands: readonly string[];
    safetyNotes: readonly string[];
  }[];
  recommendedPresetIds: readonly string[];
  recommendedPipelineIds: readonly string[];
  recommendedTemplateIds: readonly string[];
  outputs: readonly string[];
}

export function buildPlaybookPreview(playbook: IPlaybook): IPlaybookPreview {
  return {
    playbookId: playbook.id,
    title: playbook.title ?? playbook.id,
    description: playbook.description ?? null,
    steps: playbook.steps.map((s) => ({
      id: s.id,
      title: s.title,
      ...(s.description ? { description: s.description } : {}),
      commands: s.commands ?? [],
      mcpTools: s.mcpTools ?? [],
      humanReview: Boolean(s.humanReview),
      verificationCommands: s.verificationCommands ?? [],
      safetyNotes: s.safetyNotes ?? [],
    })),
    recommendedPresetIds: playbook.recommendedPresetIds ?? [],
    recommendedPipelineIds: playbook.recommendedPipelineIds ?? [],
    recommendedTemplateIds: playbook.recommendedTemplateIds ?? [],
    outputs: playbook.outputs ?? [],
  };
}

export function validatePlaybook(
  playbook: IPlaybook,
  inspection: ISharkcraftInspection,
): IPlaybookValidation {
  const issues: IPlaybookValidationIssue[] = [];

  if (!playbook.steps || playbook.steps.length === 0) {
    issues.push({
      severity: 'error',
      code: 'no-steps',
      message: 'Playbook has no steps.',
    });
  }
  const seenSteps = new Set<string>();
  for (const s of playbook.steps ?? []) {
    if (!s.id) {
      issues.push({
        severity: 'error',
        code: 'step-missing-id',
        message: `Step is missing an id (title="${s.title ?? ''}")`,
      });
      continue;
    }
    if (seenSteps.has(s.id)) {
      issues.push({
        severity: 'error',
        code: 'duplicate-step-id',
        message: `Duplicate step id "${s.id}"`,
        stepId: s.id,
      });
    }
    seenSteps.add(s.id);
    if (!s.title) {
      issues.push({
        severity: 'warning',
        code: 'step-missing-title',
        message: `Step "${s.id}" has no title.`,
        stepId: s.id,
      });
    }
    const hasAction =
      (s.commands && s.commands.length > 0) || (s.mcpTools && s.mcpTools.length > 0);
    if (!hasAction && !s.humanReview) {
      issues.push({
        severity: 'warning',
        code: 'step-empty',
        message: `Step "${s.id}" has no commands, MCP tools, or humanReview marker.`,
        stepId: s.id,
      });
    }
  }
  // Cross-reference recommended templates / pipelines / presets against the registries.
  for (const t of playbook.recommendedTemplateIds ?? []) {
    if (!inspection.templateRegistry.get(t)) {
      issues.push({
        severity: 'warning',
        code: 'missing-template',
        message: `recommendedTemplateIds references template "${t}" that is not registered.`,
      });
    }
  }
  for (const p of playbook.recommendedPipelineIds ?? []) {
    if (!inspection.pipelineRegistry.get(p)) {
      issues.push({
        severity: 'warning',
        code: 'missing-pipeline',
        message: `recommendedPipelineIds references pipeline "${p}" that is not registered.`,
      });
    }
  }
  const passed = issues.filter((i) => i.severity === 'error').length === 0;
  return {
    schema: PLAYBOOK_VALIDATION_SCHEMA,
    playbookId: playbook.id,
    issues,
    passed,
  };
}
