import type { IReviewPacketV2 } from './review-packet-v2.ts';

export interface IRenderReviewCommentV2Options {
  format?: 'github' | 'gitlab' | 'markdown' | 'html';
  maxFiles?: number;
  maxItems?: number;
}

export function renderReviewCommentV2Html(
  packet: IReviewPacketV2,
  options: Omit<IRenderReviewCommentV2Options, 'format'> = {},
): string {
  const maxFiles = options.maxFiles ?? 25;
  const maxItems = options.maxItems ?? 10;
  const esc = (s: string): string =>
    s
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  const parts: string[] = [];
  parts.push('<!doctype html>');
  parts.push('<html><head><meta charset="utf-8"><title>SharkCraft review</title>');
  parts.push('<style>');
  parts.push(
    'body{font:14px/1.4 -apple-system,BlinkMacSystemFont,sans-serif;max-width:960px;margin:24px auto;padding:0 16px;color:#1f2328;}',
  );
  parts.push('h1{font-size:20px;border-bottom:1px solid #d0d7de;padding-bottom:8px;}');
  parts.push('h2{font-size:16px;margin-top:24px;}');
  parts.push('code,pre{background:#f6f8fa;padding:1px 4px;border-radius:4px;font-size:12px;}');
  parts.push('.risk{display:inline-block;padding:2px 8px;border-radius:9999px;font-size:12px;font-weight:600;}');
  parts.push('.risk.low{background:#dafbe1;color:#1a7f37;}');
  parts.push('.risk.medium{background:#fff8c5;color:#9a6700;}');
  parts.push('.risk.high{background:#ffebe9;color:#cf222e;}');
  parts.push('.risk.critical{background:#cf222e;color:#fff;}');
  parts.push('ul{padding-left:18px;}');
  parts.push('</style></head><body>');

  parts.push(`<h1>SharkCraft review</h1>`);
  parts.push(
    `<p><strong>Risk score:</strong> ${packet.riskScore}/100 — <span class="risk ${esc(packet.impact.risk)}">${esc(packet.impact.risk)}</span></p>`,
  );
  parts.push(
    `<p>${packet.base.changedFiles.length} file(s), ${packet.impact.affectedAreas.length} area(s)</p>`,
  );

  parts.push(`<h2>Summary</h2>`);
  parts.push(`<p>${esc(packet.impact.explanation)}</p>`);

  if (packet.impact.affectedAreas.length > 0) {
    parts.push(`<h2>Changed areas</h2><ul>`);
    for (const a of packet.impact.affectedAreas.slice(0, maxItems)) {
      parts.push(`<li><code>${esc(a.kind)}</code> (${a.fileCount} files)</li>`);
    }
    parts.push(`</ul>`);
  }

  parts.push(`<h2>Changed files (${packet.base.changedFiles.length})</h2><ul>`);
  for (const f of packet.base.changedFiles.slice(0, maxFiles)) {
    parts.push(`<li>${esc(f)}</li>`);
  }
  if (packet.base.changedFiles.length > maxFiles) {
    parts.push(`<li><em>…${packet.base.changedFiles.length - maxFiles} more</em></li>`);
  }
  parts.push(`</ul>`);

  if (packet.suggestedReviewers.length > 0) {
    parts.push(`<h2>Suggested reviewers</h2><ul>`);
    for (const r of packet.suggestedReviewers.slice(0, maxItems))
      parts.push(`<li>${esc(r)}</li>`);
    parts.push(`</ul>`);
  }

  const policyErrs = packet.policy.checks.filter(
    (c) => c.severity === 'error' || c.severity === 'critical',
  );
  if (packet.base.boundaryViolations.length > 0 || policyErrs.length > 0) {
    parts.push(`<h2>Boundary / policy concerns</h2><ul>`);
    for (const v of packet.base.boundaryViolations.slice(0, maxItems)) {
      parts.push(
        `<li><code>${esc(v.file)}:${v.line}</code> — ${esc(v.message)} (${esc(v.ruleId)})</li>`,
      );
    }
    for (const c of policyErrs.slice(0, maxItems)) {
      parts.push(`<li><strong>${esc(c.title)}</strong>: ${esc(c.message)}</li>`);
    }
    parts.push(`</ul>`);
  }

  parts.push(`<h2>Test impact</h2>`);
  parts.push(`<p>Likely tests: ${packet.testImpact.likelyTestFiles.length}</p>`);
  if (packet.testImpact.missingTestFiles.length > 0) {
    parts.push(`<p>Missing tests:</p><ul>`);
    for (const m of packet.testImpact.missingTestFiles.slice(0, maxItems))
      parts.push(`<li>${esc(m)}</li>`);
    parts.push(`</ul>`);
  }

  if (packet.qualityComparison && packet.qualityComparison.regressions.length > 0) {
    parts.push(`<h2>Quality regressions</h2><ul>`);
    for (const r of packet.qualityComparison.regressions.slice(0, maxItems)) {
      parts.push(
        `<li>${esc(r.metric)}: ${r.baseline} → ${r.current} (Δ ${r.delta})</li>`,
      );
    }
    parts.push(`</ul>`);
  }

  parts.push(`<h2>Suggested commands</h2><ul>`);
  for (const c of packet.testImpact.testCommands.slice(0, maxItems))
    parts.push(`<li><code>${esc(c)}</code></li>`);
  for (const c of packet.impact.suggestedValidationCommands.slice(0, maxItems))
    parts.push(`<li><code>${esc(c)}</code></li>`);
  parts.push(`</ul>`);

  parts.push(`<h2>AI reviewer instructions</h2>`);
  parts.push(`<pre>${esc(packet.base.reviewerInstructions)}</pre>`);

  parts.push(`<p><em>Generated by SharkCraft review packet v2.</em></p>`);
  parts.push('</body></html>');
  return parts.join('\n') + '\n';
}

export function renderReviewCommentV2(
  packet: IReviewPacketV2,
  options: IRenderReviewCommentV2Options = {},
): string {
  if (options.format === 'html') {
    const opts: { maxFiles?: number; maxItems?: number } = {};
    if (options.maxFiles !== undefined) opts.maxFiles = options.maxFiles;
    if (options.maxItems !== undefined) opts.maxItems = options.maxItems;
    return renderReviewCommentV2Html(packet, opts);
  }
  const fmt = options.format ?? 'github';
  const maxFiles = options.maxFiles ?? 25;
  const maxItems = options.maxItems ?? 10;
  const lines: string[] = [];

  const heading = fmt === 'gitlab' ? '##' : '##';
  const detailsOpen = (s: string): string => (fmt === 'markdown' ? `\n${s}\n` : `<details><summary>${s}</summary>\n`);
  const detailsClose = fmt === 'markdown' ? '\n' : '\n</details>';

  lines.push(`# SharkCraft review`);
  lines.push('');
  lines.push(`**Risk score:** ${packet.riskScore}/100 — impact ${packet.impact.risk}`);
  lines.push('');
  lines.push(`${packet.base.changedFiles.length} file(s), ${packet.impact.affectedAreas.length} area(s)`);
  lines.push('');

  // Summary
  lines.push(`${heading} Summary`);
  lines.push(packet.impact.explanation);
  lines.push('');

  // Changed areas
  lines.push(`${heading} Changed areas`);
  if (packet.impact.affectedAreas.length === 0) lines.push('_None detected_');
  for (const a of packet.impact.affectedAreas.slice(0, maxItems)) {
    lines.push(`- \`${a.kind}\` (${a.fileCount} files)`);
  }
  lines.push('');

  // Files
  lines.push(detailsOpen(`Changed files (${packet.base.changedFiles.length})`));
  for (const f of packet.base.changedFiles.slice(0, maxFiles)) lines.push(`- ${f}`);
  if (packet.base.changedFiles.length > maxFiles) lines.push(`- _…${packet.base.changedFiles.length - maxFiles} more_`);
  lines.push(detailsClose);

  // Ownership
  if (packet.suggestedReviewers.length > 0) {
    lines.push(`${heading} Suggested reviewers`);
    for (const r of packet.suggestedReviewers.slice(0, maxItems)) lines.push(`- ${r}`);
    lines.push('');
  }

  // Boundary / policy
  if (packet.base.boundaryViolations.length > 0 || packet.policy.summary.error > 0) {
    lines.push(`${heading} Boundary / policy concerns`);
    for (const v of packet.base.boundaryViolations.slice(0, maxItems)) {
      lines.push(`- \`${v.file}:${v.line}\` — ${v.message} (${v.ruleId})`);
    }
    const errs = packet.policy.checks.filter((c) => c.severity === 'error' || c.severity === 'critical');
    for (const c of errs.slice(0, maxItems)) lines.push(`- ${c.title}: ${c.message}`);
    lines.push('');
  }

  // Test impact
  lines.push(`${heading} Test impact`);
  lines.push(`Likely tests: ${packet.testImpact.likelyTestFiles.length}`);
  if (packet.testImpact.missingTestFiles.length > 0) {
    lines.push('Missing tests:');
    for (const m of packet.testImpact.missingTestFiles.slice(0, maxItems)) lines.push(`- ${m}`);
  }
  lines.push('');

  // Quality regressions
  if (packet.qualityComparison && packet.qualityComparison.regressions.length > 0) {
    lines.push(`${heading} Quality regressions`);
    for (const r of packet.qualityComparison.regressions.slice(0, maxItems)) {
      lines.push(`- ${r.metric}: ${r.baseline} → ${r.current} (Δ ${r.delta})`);
    }
    lines.push('');
  }

  // Commands
  lines.push(`${heading} Suggested commands`);
  for (const c of packet.testImpact.testCommands.slice(0, maxItems)) lines.push(`- \`${c}\``);
  for (const c of packet.impact.suggestedValidationCommands.slice(0, maxItems)) lines.push(`- \`${c}\``);
  lines.push('');

  // AI reviewer instructions
  lines.push(`${heading} AI reviewer instructions`);
  lines.push(packet.base.reviewerInstructions);
  lines.push('');

  // Artifacts
  lines.push(`_Generated by SharkCraft review packet v2._`);

  return lines.join('\n') + '\n';
}
