/**
 * Convert an {@link IOnboardingPlan} into populated `sharkcraft/*.ts`
 * file contents — the engine behind `shrk init --infer --write`.
 *
 * Design goals:
 *
 *   - **Populated, not advisory.** The existing `writeOnboardingDrafts`
 *     emits files into `sharkcraft/onboarding/` and asks the user to
 *     adopt by hand. This module emits directly to `sharkcraft/`-root
 *     files so a `shrk init --infer --write` user gets a working
 *     project on day 1.
 *
 *   - **Honest about confidence.** Inferred entries are tagged with
 *     their source signal and confidence; medium-confidence rows get a
 *     `// TODO: review` marker on the emitted line. The user can see
 *     exactly what was inferred vs hand-curated. Low-confidence rows
 *     are dropped from the populated file and reported in the
 *     companion `.inferred-report.md` so the user can find them.
 *
 *   - **Self-contained output.** Generated files declare their own
 *     `defineKnowledgeEntry` / `definePathConvention` stubs — no
 *     `@shrkcrft/*` imports, matching the local-mirror pattern from
 *     `packages/presets/src/emit/synthesize-files.ts`.
 *
 *   - **Deterministic.** Same input → same output, byte-for-byte.
 *     Sort lists by id where they're rendered together.
 *
 *   - **Idempotent at the file level.** The caller decides write vs
 *     dry-run + force; this module only produces strings.
 */

import type { IOnboardingPlan } from './onboarding.ts';

// ─── Public types ────────────────────────────────────────────────────────────

export interface IInferredFile {
  /** Path relative to sharkcraft/. */
  path: string;
  content: string;
  /** Which kind of file this is — drives default naming in the report. */
  kind: 'config' | 'paths' | 'rules' | 'boundaries' | 'pipelines' | 'knowledge' | 'report-md' | 'report-json';
}

export interface IInferenceConfidenceReport {
  /** Entries adopted directly into the populated files (high confidence). */
  adoptedHigh: readonly IConfidenceLine[];
  /** Entries adopted with a `// TODO: review` marker (medium confidence). */
  adoptedMedium: readonly IConfidenceLine[];
  /** Entries left out of the populated files (low confidence / no signal). */
  dropped: readonly IConfidenceLine[];
  /** Author-by-hand suggestions — things shrk can't infer. */
  notInferable: readonly string[];
}

export interface IConfidenceLine {
  kind: 'rule' | 'path' | 'boundary' | 'pipeline' | 'template' | 'verification';
  id: string;
  title: string;
  /** Why this signal fired (from the onboarding plan). */
  reason: string;
}

export interface IInferenceResult {
  files: readonly IInferredFile[];
  report: IInferenceConfidenceReport;
}

// ─── Local-mirror preambles (match presets' synthesize-files.ts) ─────────────

const KNOWLEDGE_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
// Generated by \`shrk init --infer\`. Edit freely.

const KnowledgePriority = {
  Critical: 'critical',
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;

const KnowledgeType = {
  Rule: 'rule',
  Path: 'path',
  Template: 'template',
  Architecture: 'architecture',
  Technical: 'technical',
  Convention: 'convention',
  Workflow: 'workflow',
  Warning: 'warning',
} as const;

function defineKnowledgeEntry<T>(entry: T): T {
  return entry;
}
`;

const PIPELINE_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
// Generated by \`shrk init --infer\`. Edit freely.

function definePipeline<T>(pipeline: T): T {
  return pipeline;
}
`;

// ─── Confidence triage ───────────────────────────────────────────────────────

const HIGH_CONFIDENCE_RULE_IDS: ReadonlySet<string> = new Set([
  'typescript.strict-mode',
  'project.package-manager',
]);

/** Map an inferred-rule priority to a {high|medium|low} adoption tier. */
function ruleTier(rule: { priority: string; id: string }): 'high' | 'medium' | 'low' {
  // Promote known-canonical rules.
  if (HIGH_CONFIDENCE_RULE_IDS.has(rule.id)) return 'high';
  const p = rule.priority.toLowerCase();
  if (p === 'critical' || p === 'high') return 'high';
  if (p === 'medium') return 'medium';
  return 'low';
}

function pathTier(path: { id: string; patterns: readonly string[] }): 'high' | 'medium' | 'low' {
  // Path conventions are inferred from disk presence — if we found the
  // directory, the convention is real. The only "low" case is when the
  // patterns list is empty (couldn't pin a concrete location).
  if (path.patterns.length === 0) return 'low';
  return 'high';
}

function boundaryTier(rule: { from: readonly string[]; forbiddenImports?: readonly string[] }): 'high' | 'medium' | 'low' {
  // Boundary rules require BOTH a from-pattern AND a forbidden list to
  // be enforceable. Without forbidden imports, the rule is a label,
  // not a gate.
  if (rule.from.length === 0) return 'low';
  if (!rule.forbiddenImports || rule.forbiddenImports.length === 0) return 'medium';
  return 'high';
}

function pipelineTier(pipeline: { steps: readonly string[] }): 'high' | 'medium' | 'low' {
  // Pipelines with concrete steps that map to verification commands
  // are higher-confidence than generic feature-dev outlines.
  if (pipeline.steps.length === 0) return 'low';
  if (pipeline.steps.length <= 2) return 'medium';
  return 'high';
}

// ─── Renderers ──────────────────────────────────────────────────────────────

function renderPath(p: { id: string; title: string; content: string; patterns: readonly string[]; reason: string }, tier: 'high' | 'medium'): string {
  const todo = tier === 'medium' ? '// TODO: review — confidence: medium\n  ' : '';
  const primaryPath = p.patterns[0]?.replace(/\/\*\*.*$/, '').replace(/\/\*$/, '') ?? '';
  return `  ${todo}defineKnowledgeEntry({
    id: ${JSON.stringify(p.id)},
    title: ${JSON.stringify(p.title)},
    type: KnowledgeType.Path,
    priority: KnowledgePriority.High,
    tags: ['paths', 'inferred'],
    scope: ['inferred'],
    appliesWhen: ['generate-code'],
    content: ${JSON.stringify(p.content)},
    metadata: {
      path: ${JSON.stringify(primaryPath)},
      patterns: ${JSON.stringify(p.patterns)},
      inferredFrom: ${JSON.stringify(p.reason)},
    },
  })`;
}

function renderRule(r: { id: string; title: string; content: string; priority: string; source: string; reason: string }, tier: 'high' | 'medium'): string {
  const todo = tier === 'medium' ? '// TODO: review — confidence: medium\n  ' : '';
  const priority =
    r.priority === 'critical' ? 'KnowledgePriority.Critical'
    : r.priority === 'high' ? 'KnowledgePriority.High'
    : r.priority === 'medium' ? 'KnowledgePriority.Medium'
    : 'KnowledgePriority.Low';
  return `  ${todo}defineKnowledgeEntry({
    id: ${JSON.stringify(r.id)},
    title: ${JSON.stringify(r.title)},
    type: KnowledgeType.Rule,
    priority: ${priority},
    tags: ['inferred', ${JSON.stringify(r.source)}],
    scope: ['inferred'],
    appliesWhen: ['generate-code', 'review'],
    content: ${JSON.stringify(r.content)},
    metadata: {
      inferredFrom: ${JSON.stringify(r.reason)},
      source: ${JSON.stringify(r.source)},
    },
  })`;
}

function renderBoundary(b: {
  id: string;
  title: string;
  severity: 'error' | 'warning';
  from: readonly string[];
  forbiddenImports?: readonly string[];
  allowedImports?: readonly string[];
  suggestedFix: string;
  reason: string;
}, tier: 'high' | 'medium'): string {
  const todo = tier === 'medium' ? '// TODO: review — confidence: medium\n  ' : '';
  const forbidden = b.forbiddenImports && b.forbiddenImports.length > 0
    ? `\n    forbiddenImports: ${JSON.stringify(b.forbiddenImports)},`
    : '';
  const allowed = b.allowedImports && b.allowedImports.length > 0
    ? `\n    allowedImports: ${JSON.stringify(b.allowedImports)},`
    : '';
  return `  ${todo}{
    id: ${JSON.stringify(b.id)},
    title: ${JSON.stringify(b.title)},
    severity: ${JSON.stringify(b.severity)},
    from: ${JSON.stringify(b.from)},${forbidden}${allowed}
    suggestedFix: ${JSON.stringify(b.suggestedFix)},
    inferredFrom: ${JSON.stringify(b.reason)},
  }`;
}

function renderPipeline(p: { id: string; title: string; description: string; steps: readonly string[]; reason: string }, tier: 'high' | 'medium'): string {
  const todo = tier === 'medium' ? '// TODO: review — confidence: medium\n  ' : '';
  const stepLines = p.steps
    .map((s) => `      { id: ${JSON.stringify(s)}, type: 'command', description: ${JSON.stringify(s)} }`)
    .join(',\n');
  return `  ${todo}definePipeline({
    id: ${JSON.stringify(p.id)},
    title: ${JSON.stringify(p.title)},
    description: ${JSON.stringify(p.description)},
    tags: ['inferred'],
    steps: [
${stepLines}
    ],
    metadata: {
      inferredFrom: ${JSON.stringify(p.reason)},
    },
  })`;
}

// ─── File builders ──────────────────────────────────────────────────────────

function buildConfigFile(opts: {
  projectName: string;
  description: string;
  includePaths: boolean;
  includeRules: boolean;
  includeBoundaries: boolean;
  includePipelines: boolean;
}): string {
  return (
    `// Generated by \`shrk init --infer\`. Edit freely; SharkCraft will not\n` +
    `// regenerate this file. Re-run \`shrk init --infer --force\` to overwrite.\n\n` +
    `const config = {\n` +
    `  projectName: ${JSON.stringify(opts.projectName)},\n` +
    `  description: ${JSON.stringify(opts.description)},\n` +
    `  pathFiles: ${JSON.stringify(opts.includePaths ? ['paths.ts'] : [])},\n` +
    `  ruleFiles: ${JSON.stringify(opts.includeRules ? ['rules.ts'] : [])},\n` +
    `  boundaryFiles: ${JSON.stringify(opts.includeBoundaries ? ['boundaries.ts'] : [])},\n` +
    `  pipelineFiles: ${JSON.stringify(opts.includePipelines ? ['pipelines.ts'] : [])},\n` +
    `  knowledgeFiles: ${JSON.stringify(['knowledge.ts'])},\n` +
    `  templateFiles: ${JSON.stringify([])},\n` +
    `  docsFiles: ${JSON.stringify([])},\n` +
    `  defaultMaxTokens: 3500,\n` +
    `};\n\nexport default config;\n`
  );
}

function buildPathsFile(rendered: readonly string[]): string {
  return (
    KNOWLEDGE_HELPERS +
    '\nconst paths = [\n' +
    rendered.join(',\n') +
    (rendered.length > 0 ? ',\n' : '') +
    '];\n\nexport default paths;\n'
  );
}

function buildRulesFile(rendered: readonly string[]): string {
  return (
    KNOWLEDGE_HELPERS +
    '\nconst rules = [\n' +
    rendered.join(',\n') +
    (rendered.length > 0 ? ',\n' : '') +
    '];\n\nexport default rules;\n'
  );
}

function buildBoundariesFile(rendered: readonly string[]): string {
  return (
    '// Generated by `shrk init --infer`. Plain default-export array — the\n' +
    '// boundaries loader accepts any object with id/title/severity/from.\n\n' +
    'export default [\n' +
    rendered.join(',\n') +
    (rendered.length > 0 ? ',\n' : '') +
    '];\n'
  );
}

function buildPipelinesFile(rendered: readonly string[]): string {
  return (
    PIPELINE_HELPERS +
    '\nconst pipelines = [\n' +
    rendered.join(',\n') +
    (rendered.length > 0 ? ',\n' : '') +
    '];\n\nexport default pipelines;\n'
  );
}

function buildKnowledgeSeed(projectName: string, description: string): string {
  // Minimal but useful knowledge seed — these aren't really inferable,
  // but every repo benefits from the agent-briefing + safety baseline.
  return (
    KNOWLEDGE_HELPERS +
    '\n' +
    `export const projectOverview = defineKnowledgeEntry({
  id: 'project.overview',
  title: ${JSON.stringify(projectName + ' — project overview')},
  type: KnowledgeType.Architecture,
  priority: KnowledgePriority.High,
  tags: ['overview', 'inferred'],
  scope: ['inferred'],
  appliesWhen: ['onboard', 'plan-work'],
  summary: ${JSON.stringify(description || 'High-level overview of this project.')},
  content: ${JSON.stringify(description || 'High-level overview of this project. Generated by shrk init --infer; replace with project-specific context.')},
});

export const agentBriefing = defineKnowledgeEntry({
  id: 'agent.briefing',
  title: 'AI agent briefing',
  type: KnowledgeType.Convention,
  priority: KnowledgePriority.Critical,
  tags: ['agent', 'safety'],
  scope: ['agent'],
  appliesWhen: ['agent-start', 'agent-plan'],
  content: \`When working in this repo as an AI agent:
1. Read \\\`shrk brief\\\` for the focused project context (rules + paths + verification).
2. Use \\\`shrk task "<task>"\\\` to get a per-task packet (relevant rules + templates + commands).
3. Generate code via \\\`shrk gen <template> <name> --dry-run --save-plan plan.json\\\`, then apply with \\\`shrk apply plan.json --verify-signature --validate\\\`.
4. Never bypass \\\`shrk check boundaries\\\` — it gates architecture violations.\`,
});

export const generationSafety = defineKnowledgeEntry({
  id: 'safety.generation',
  title: 'Generation safety',
  type: KnowledgeType.Warning,
  priority: KnowledgePriority.Critical,
  tags: ['safety', 'generation'],
  scope: ['generation'],
  appliesWhen: ['generate-code', 'overwrite-file'],
  content: \`shrk gen defaults to dry-run. A real write requires --write AND a clean plan (no conflicts). AI agents must call create_generation_plan via MCP first — never write files directly through MCP.\`,
});

export default [projectOverview, agentBriefing, generationSafety];
`
  );
}

// ─── Confidence report renderers ─────────────────────────────────────────────

function buildReportMarkdown(report: IInferenceConfidenceReport, projectName: string): string {
  const lines: string[] = [];
  lines.push(`# Inferred from your codebase`);
  lines.push('');
  lines.push(
    `\`shrk init --infer\` scanned ${projectName} and produced the populated ` +
      `\`sharkcraft/*.ts\` files alongside this report. Re-run with \`--force\` to regenerate.`,
  );
  lines.push('');
  lines.push(`## ✅ Adopted directly (${report.adoptedHigh.length} entries — high confidence)`);
  lines.push('');
  if (report.adoptedHigh.length === 0) {
    lines.push('_None._');
  } else {
    for (const line of report.adoptedHigh) {
      lines.push(`- **[${line.kind}] \`${line.id}\`** — ${line.title} _(${line.reason})_`);
    }
  }
  lines.push('');
  lines.push(`## 🟡 Adopted with review marker (${report.adoptedMedium.length} entries — medium confidence)`);
  lines.push('');
  lines.push(
    'These entries were included in the populated files with a `// TODO: review` ' +
      'comment. Read them, confirm they match your team\'s actual practice, then remove the marker.',
  );
  lines.push('');
  if (report.adoptedMedium.length === 0) {
    lines.push('_None._');
  } else {
    for (const line of report.adoptedMedium) {
      lines.push(`- **[${line.kind}] \`${line.id}\`** — ${line.title} _(${line.reason})_`);
    }
  }
  lines.push('');
  lines.push(`## ⚠️ Not adopted (${report.dropped.length} entries — low confidence)`);
  lines.push('');
  lines.push(
    'These entries had weak signals — either incomplete data or generic patterns that ' +
      'might not reflect your real conventions. Review the draft versions under ' +
      '`sharkcraft/onboarding/` (after running `shrk onboard --write-drafts`) and adopt any that apply.',
  );
  lines.push('');
  if (report.dropped.length === 0) {
    lines.push('_None — all signals were strong enough to adopt._');
  } else {
    for (const line of report.dropped) {
      lines.push(`- **[${line.kind}] \`${line.id}\`** — ${line.title} _(${line.reason})_`);
    }
  }
  lines.push('');
  lines.push(`## ✍️ What shrk can't infer (author these by hand)`);
  lines.push('');
  lines.push(
    'These categories rely on team knowledge that\'s not visible in code or config. ' +
      'Add them to `sharkcraft/knowledge.ts` to make Claude aware:',
  );
  lines.push('');
  for (const item of report.notInferable) lines.push(`- ${item}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    `_Generated by \`shrk init --infer\`. This report is regenerated each ` +
      `time you re-run with \`--force\`._`,
  );
  return lines.join('\n') + '\n';
}

const NOT_INFERABLE_DEFAULTS: readonly string[] = [
  'Project-specific architectural decisions ("we chose X over Y because…").',
  'Deprecated paths / legacy code to avoid ("don\'t add new code to legacy/").',
  'Non-obvious conventions ("our pagination uses cursor, not offset").',
  'Cross-cutting concerns ("all writes go through the audit-log middleware").',
  'Recently-changed patterns ("DTOs migrated to class-validator last month — old code uses Zod").',
  'Team workflow conventions ("review with two approvals before merge to main").',
];

// ─── Public entry point ─────────────────────────────────────────────────────

/**
 * Convert an {@link IOnboardingPlan} into a populated set of
 * `sharkcraft/*.ts` files plus a companion confidence report.
 *
 * The caller is responsible for actually writing the files; this
 * function is pure (input plan → output strings).
 */
export function synthesizeFromOnboarding(
  plan: IOnboardingPlan,
): IInferenceResult {
  const report: {
    adoptedHigh: IConfidenceLine[];
    adoptedMedium: IConfidenceLine[];
    dropped: IConfidenceLine[];
  } = { adoptedHigh: [], adoptedMedium: [], dropped: [] };

  // ── Triage paths ────────────────────────────────────────────────────
  const renderedPaths: string[] = [];
  for (const p of [...plan.inferredPathConventions].sort((a, b) => a.id.localeCompare(b.id))) {
    const tier = pathTier(p);
    if (tier === 'low') {
      report.dropped.push({ kind: 'path', id: p.id, title: p.title, reason: p.reason });
      continue;
    }
    renderedPaths.push(renderPath(p, tier));
    (tier === 'high' ? report.adoptedHigh : report.adoptedMedium).push({
      kind: 'path',
      id: p.id,
      title: p.title,
      reason: p.reason,
    });
  }

  // ── Triage rules ────────────────────────────────────────────────────
  const renderedRules: string[] = [];
  for (const r of [...plan.inferredRules].sort((a, b) => a.id.localeCompare(b.id))) {
    const tier = ruleTier(r);
    if (tier === 'low') {
      report.dropped.push({ kind: 'rule', id: r.id, title: r.title, reason: r.reason });
      continue;
    }
    renderedRules.push(renderRule(r, tier));
    (tier === 'high' ? report.adoptedHigh : report.adoptedMedium).push({
      kind: 'rule',
      id: r.id,
      title: r.title,
      reason: r.reason,
    });
  }

  // ── Triage boundaries ──────────────────────────────────────────────
  const renderedBoundaries: string[] = [];
  for (const b of [...plan.inferredBoundaryRules].sort((a, b2) => a.id.localeCompare(b2.id))) {
    const tier = boundaryTier(b);
    if (tier === 'low') {
      report.dropped.push({ kind: 'boundary', id: b.id, title: b.title, reason: b.reason });
      continue;
    }
    renderedBoundaries.push(renderBoundary(b, tier));
    (tier === 'high' ? report.adoptedHigh : report.adoptedMedium).push({
      kind: 'boundary',
      id: b.id,
      title: b.title,
      reason: b.reason,
    });
  }

  // ── Triage pipelines ───────────────────────────────────────────────
  const renderedPipelines: string[] = [];
  for (const p of [...plan.inferredPipelines].sort((a, b) => a.id.localeCompare(b.id))) {
    const tier = pipelineTier(p);
    if (tier === 'low') {
      report.dropped.push({ kind: 'pipeline', id: p.id, title: p.title, reason: p.reason });
      continue;
    }
    renderedPipelines.push(renderPipeline(p, tier));
    (tier === 'high' ? report.adoptedHigh : report.adoptedMedium).push({
      kind: 'pipeline',
      id: p.id,
      title: p.title,
      reason: p.reason,
    });
  }

  // ── Templates are dropped wholesale into the report — emitting a
  //    runnable template from inference is too speculative to populate
  //    automatically. The user gets them as drafts via `shrk onboard
  //    --write-drafts`.
  for (const t of plan.inferredTemplateCandidates) {
    report.dropped.push({
      kind: 'template',
      id: t.id,
      title: t.name,
      reason: `${t.reason} (templates require manual review; see sharkcraft/onboarding/inferred-templates.draft.ts after \`shrk onboard --write-drafts\`)`,
    });
  }

  // ── Verification commands surface in the report only (consumed via
  //    sharkcraft.config.ts verificationCommands[]; not emitted as
  //    `sharkcraft/*.ts` here to avoid duplicating config shape).
  for (const v of plan.inferredVerificationCommands) {
    report.adoptedHigh.push({
      kind: 'verification',
      id: v.id,
      title: `${v.label}: \`${v.command}\``,
      reason: v.reason,
    });
  }

  const projectName = plan.projectSummary.projectName ?? 'project';
  const description = plan.projectSummary.description ?? '';

  const files: IInferredFile[] = [];

  files.push({
    path: 'sharkcraft.config.ts',
    kind: 'config',
    content: buildConfigFile({
      projectName,
      description,
      includePaths: renderedPaths.length > 0,
      includeRules: renderedRules.length > 0,
      includeBoundaries: renderedBoundaries.length > 0,
      includePipelines: renderedPipelines.length > 0,
    }),
  });

  files.push({
    path: 'knowledge.ts',
    kind: 'knowledge',
    content: buildKnowledgeSeed(projectName, description),
  });

  if (renderedPaths.length > 0) {
    files.push({ path: 'paths.ts', kind: 'paths', content: buildPathsFile(renderedPaths) });
  }
  if (renderedRules.length > 0) {
    files.push({ path: 'rules.ts', kind: 'rules', content: buildRulesFile(renderedRules) });
  }
  if (renderedBoundaries.length > 0) {
    files.push({
      path: 'boundaries.ts',
      kind: 'boundaries',
      content: buildBoundariesFile(renderedBoundaries),
    });
  }
  if (renderedPipelines.length > 0) {
    files.push({
      path: 'pipelines.ts',
      kind: 'pipelines',
      content: buildPipelinesFile(renderedPipelines),
    });
  }

  const fullReport: IInferenceConfidenceReport = {
    adoptedHigh: report.adoptedHigh,
    adoptedMedium: report.adoptedMedium,
    dropped: report.dropped,
    notInferable: NOT_INFERABLE_DEFAULTS,
  };

  files.push({
    path: '.inferred-report.md',
    kind: 'report-md',
    content: buildReportMarkdown(fullReport, projectName),
  });

  files.push({
    path: '.inferred-report.json',
    kind: 'report-json',
    content: JSON.stringify({
      schema: 'sharkcraft.inferred-report/v1',
      generatedAt: new Date().toISOString().slice(0, 10),
      projectName,
      adoptedHigh: fullReport.adoptedHigh,
      adoptedMedium: fullReport.adoptedMedium,
      dropped: fullReport.dropped,
      notInferable: fullReport.notInferable,
    }, null, 2) + '\n',
  });

  return { files, report: fullReport };
}
