#!/usr/bin/env bun
// release-preflight: full chain that gates a v0.1.0-alpha.N tag.
//
// Runs each step in order, captures the exit code, surfaces a final summary,
// and exits non-zero if any step fails. Intended to be the one command a
// release engineer runs on a clean checkout before tagging.
import { spawnSync } from 'node:child_process';
import { readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

interface IStep {
  name: string;
  /** Spawn-based step: external command + args. Mutually exclusive with `run`. */
  cmd?: string;
  args?: readonly string[];
  /**
   * In-process step: returns a process-style exit code (0 = ok). Used for
   * checks that need TS logic instead of shelling out to a standalone script.
   */
  run?: () => number;
  /** When true, a failure here aborts the rest of the chain. */
  required: boolean;
}

interface IStepResult {
  step: IStep;
  status: 'ok' | 'failed' | 'skipped';
  durationMs: number;
  exitCode: number | null;
}

const withNodeCompat = process.argv.includes('--with-node-compat');
const withE2E = process.argv.includes('--with-e2e');

// Resolve `shrk` to the local workspace CLI (`bun packages/cli/src/main.ts …`)
// so preflight runs against THIS repo's engine instead of whatever the global
// `shrk` binary on PATH happens to point at. Important when dogfooding on a
// machine that has shrk linked from another monorepo.
const LOCAL_SHRK = ['packages/cli/src/main.ts'];

const TAXONOMY_DOC = 'docs/commands-taxonomy.md';

/**
 * D5 — `docs/commands-taxonomy.md` must mirror the live command catalog. The
 * doc is generated by `shrk commands taxonomy --write-docs`; when the catalog
 * changes without regenerating the doc it silently drifts. We regenerate into a
 * temp file (the same write path as `--write-docs`, so no working-tree
 * mutation) and byte-compare against the committed doc — the in-process
 * equivalent of a regenerate-then-`git diff --exit-code`.
 *
 * Returns 1 only on a genuine drift. Returns 0 when in sync OR when the
 * generator can't be reached in this env (degrade to a printed warning rather
 * than block a release on a missing/broken local CLI).
 */
function checkTaxonomyDrift(): number {
  const committedPath = resolve(process.cwd(), TAXONOMY_DOC);
  let committed: string;
  try {
    committed = readFileSync(committedPath, 'utf8');
  } catch {
    process.stdout.write(
      `[taxonomy-drift] WARN: ${TAXONOMY_DOC} not found — skipping freshness check (non-blocking).\n`,
    );
    return 0;
  }
  const tmp = join(tmpdir(), `shrk-taxonomy-${process.pid}-${Date.now()}.md`);
  const res = spawnSync('bun', [...LOCAL_SHRK, 'commands', 'taxonomy', '--output', tmp], {
    encoding: 'utf8',
  });
  let generated: string | null = null;
  if (res.status === 0) {
    try {
      generated = readFileSync(tmp, 'utf8');
    } catch {
      generated = null;
    }
  }
  try {
    rmSync(tmp, { force: true });
  } catch {
    /* best-effort temp cleanup */
  }
  if (generated === null) {
    process.stdout.write(
      '[taxonomy-drift] WARN: `shrk commands taxonomy` unavailable in this env — ' +
        'skipping freshness check (non-blocking).\n',
    );
    if (res.stderr) process.stdout.write(String(res.stderr));
    return 0;
  }
  if (generated === committed) {
    process.stdout.write(`${TAXONOMY_DOC} is in sync with the command catalog.\n`);
    return 0;
  }
  process.stdout.write(
    `${TAXONOMY_DOC} has drifted from the command catalog.\n` +
      'Run `shrk commands taxonomy --write-docs` and commit the result.\n',
  );
  return 1;
}

const STEPS: readonly IStep[] = [
  { name: 'typecheck', cmd: 'bun', args: ['x', 'tsc', '-p', 'tsconfig.base.json', '--noEmit'], required: true },
  // R37: hard-gate on import-hygiene errors. `shrk check imports` exits
  // non-zero on any `error`-severity finding, including lazy
  // `require('node:*')`. Warnings (dynamic imports) do not block.
  { name: 'import-hygiene', cmd: 'bun', args: [...LOCAL_SHRK, 'check', 'imports'], required: true },
  // R58 — `docs/schemas/` must mirror the in-memory schema registry.
  // Run `shrk schemas emit --write` to refresh.
  { name: 'schemas-drift', cmd: 'bun', args: [...LOCAL_SHRK, 'schemas', 'emit', '--check'], required: true },
  // D5 — `docs/commands-taxonomy.md` must mirror the live command catalog
  // (generated by `shrk commands taxonomy --write-docs`). Runs in-process so it
  // can reuse the local-CLI resolution and degrade gracefully: a drift fails
  // preflight, but a missing/broken generator only warns (non-blocking). Kept
  // `required: false` so a docs drift surfaces in the summary without aborting
  // the more fundamental typecheck/test steps below.
  { name: 'taxonomy-drift', run: checkTaxonomyDrift, required: false },
  // R58 — every doctor verb must emit parseable JSON on --json, including
  // error paths. Regressions surface here.
  { name: 'doctor-json-audit', cmd: 'bun', args: ['run', 'audit:doctor-json'], required: true },
  // --timeout 30000: spawn-based integration tests shell out to a full
  // `bun main.ts <cmd>` (the helpers cap that at 60s via spawnSync). Under the
  // load of a full release run those spawns can exceed Bun's default 5s
  // per-test timeout, producing flaky "timed out after 5000ms" failures that
  // are not real regressions. 30s gives ample headroom while still catching a
  // genuine hang. Keep in sync with the `test` script + ci.yml.
  { name: 'tests', cmd: 'bun', args: ['test', '--timeout', '30000'], required: true },
  { name: 'build-dist', cmd: 'bun', args: ['run', 'build:dist'], required: true },
  { name: 'dashboard-build', cmd: 'bun', args: ['run', 'dashboard:build'], required: true },
  { name: 'publish-dry-run', cmd: 'bun', args: ['run', 'publish:dry-run'], required: true },
  { name: 'release-check', cmd: 'bun', args: ['run', 'release:check'], required: false },
  { name: 'install-smoke-test', cmd: 'bun', args: ['run', 'release:smoke-test'], required: false },
  // Node compatibility audit. Always runs as a non-blocking warning gate so we
  // surface Bun.* regressions in production source without breaking the
  // release. Pass --with-node-compat to additionally probe the built dist
  // under node (still non-blocking).
  { name: 'compat-node', cmd: 'bun', args: ['run', 'compat:node'], required: false },
  ...(withNodeCompat
    ? [
        {
          name: 'compat-node-runtime',
          cmd: 'bun',
          args: ['run', 'scripts/compat-node.ts', '--runtime', '--cli'] as readonly string[],
          required: false,
        },
      ]
    : []),
  // Playwright dashboard E2E. Opt-in via --with-e2e because the suite
  // requires `bun run e2e:install` (downloads Chromium) and adds ~30s to
  // the run. Treated as non-blocking by design until proven stable in CI.
  ...(withE2E
    ? [
        {
          name: 'dashboard-e2e',
          cmd: 'bun',
          args: ['run', 'test:e2e:dashboard'] as readonly string[],
          required: false,
        },
      ]
    : []),
];

const results: IStepResult[] = [];
let aborted = false;

for (const step of STEPS) {
  if (aborted) {
    results.push({ step, status: 'skipped', durationMs: 0, exitCode: null });
    continue;
  }
  process.stdout.write(`\n=== ${step.name} ===\n`);
  const start = Date.now();
  let exitCode: number | null;
  if (step.run) {
    exitCode = step.run();
  } else {
    const res = spawnSync(step.cmd as string, [...(step.args ?? [])], { stdio: 'inherit' });
    exitCode = res.status;
  }
  const durationMs = Date.now() - start;
  if (exitCode === 0) {
    results.push({ step, status: 'ok', durationMs, exitCode: 0 });
    continue;
  }
  results.push({ step, status: 'failed', durationMs, exitCode: exitCode ?? -1 });
  if (step.required) {
    aborted = true;
  }
}

process.stdout.write('\n=== Preflight summary ===\n');
let failed = 0;
let skipped = 0;
for (const r of results) {
  const tag =
    r.status === 'ok'
      ? 'OK     '
      : r.status === 'failed'
        ? 'FAILED '
        : 'SKIPPED';
  process.stdout.write(
    `  ${tag} ${r.step.name.padEnd(22)} ${`${r.durationMs}ms`.padStart(8)}` +
      (r.exitCode !== null && r.status !== 'ok' ? `  (exit ${r.exitCode})` : '') +
      '\n',
  );
  if (r.status === 'failed') failed += 1;
  if (r.status === 'skipped') skipped += 1;
}

if (failed > 0) {
  process.stdout.write(
    `\n[release-preflight] ${failed} step(s) failed, ${skipped} skipped — NOT ready to tag.\n`,
  );
  process.exit(1);
}
process.stdout.write('\n[release-preflight] all required steps passed ✓ — ready to tag\n');
