/**
 * Round-3 surfaces: the in-file `handMaintainedMarker`, `gates check --strict`,
 * and a verdict-level proof that the coverage read memo cannot go stale.
 *
 * The bugs this file exists to prevent:
 *   • a marker that a GENERATED file's own header also satisfies, so every file
 *     exempts itself from the check the marker was added to refine;
 *   • a zero-warning CI having no supported way to fail on warnings;
 *   • a cached scan answering "nothing drifted" about a file that just changed.
 */
import { describe, expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { gatesCheckCommand, gatesCoverageCommand } from '../commands/gates.command.ts';
import { generatedCheckCommand, generatedExplainCommand } from '../commands/generated.command.ts';
import { ExitCode } from '../exit-codes.ts';
import type { ParsedArgs } from '../command-registry.ts';

function args(root: string, positional: string[], flags: Record<string, string | boolean> = {}): ParsedArgs {
  return {
    positional,
    flags: new Map<string, string | boolean>([['cwd', root], ...Object.entries(flags)]),
    multiFlags: new Map(),
  };
}

function capture(): () => string {
  const origOut = process.stdout.write.bind(process.stdout);
  const origErr = process.stderr.write.bind(process.stderr);
  let body = '';
  const sink = ((c: string | Uint8Array): boolean => {
    body += typeof c === 'string' ? c : Buffer.from(c).toString('utf8');
    return true;
  }) as typeof process.stdout.write;
  process.stdout.write = sink;
  process.stderr.write = sink as typeof process.stderr.write;
  return () => {
    process.stdout.write = origOut;
    process.stderr.write = origErr;
    return body;
  };
}

async function run(h: { run(a: ParsedArgs): Promise<number> | number }, a: ParsedArgs) {
  const restore = capture();
  try {
    const code = await h.run(a);
    return { code, out: restore() };
  } catch (e) {
    restore();
    throw e;
  }
}

/** A mixed tree: one generated file, one marker-blessed, one unclassified. */
function markerFixture(marker: string): string {
  const root = mkdtempSync(join(tmpdir(), 'shrk-r69-'));
  mkdirSync(join(root, 'sharkcraft'), { recursive: true });
  mkdirSync(join(root, 'src', 'generated'), { recursive: true });
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'fx', version: '0.0.0' }));
  writeFileSync(join(root, 'src/generated/A.ts'), '// GENERATED by gen — do not edit\nexport const A = 1;\n');
  writeFileSync(join(root, 'src/generated/B.ts'), '// HAND-AUTHORED, NOT GENERATED\nexport const B = 2;\n');
  writeFileSync(join(root, 'src/generated/C.ts'), 'export const C = 3;\n');
  writeFileSync(
    join(root, 'sharkcraft', 'sharkcraft.config.ts'),
    `export default {
  generatedArtifacts: [{
    id: 'views',
    generatedGlob: ['src/generated/*.ts'],
    provenanceHeader: { mustMatch: 'GENERATED .* do not edit', withinLines: 5 },
    handMaintainedMarker: ${JSON.stringify(marker)},
  }],
};
`,
  );
  return root;
}

describe('handMaintainedMarker — the bless lives in the file', () => {
  test('a marked file is exempt from the header check without a config entry', async () => {
    const root = markerFixture('HAND-AUTHORED, NOT GENERATED');
    try {
      const { out } = await run(generatedExplainCommand, args(root, [], { id: 'views' }));
      expect(out).toContain('src/generated/B.ts  (in-file marker)');
      // B is exempt; C — neither headered nor marked — is still loud.
      expect(out).not.toMatch(/missing-header\] src\/generated\/B\.ts/);
      expect(out).toContain('[missing-header] src/generated/C.ts');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('an unmarked, unheadered file is STILL a finding — the marker is a third classification, not an escape', async () => {
    const root = markerFixture('HAND-AUTHORED, NOT GENERATED');
    try {
      const { code, out } = await run(generatedCheckCommand, args(root, [], { 'headers-only': true }));
      expect(code).toBe(ExitCode.Failure);
      expect(out).toContain('src/generated/C.ts');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('a marker that OVERLAPS the generated header is refused at config load', async () => {
    // Otherwise every generated file's own header exempts it from the header
    // check — the rule would pass forever while enforcing nothing.
    const root = markerFixture('GENERATED');
    try {
      const { code, out } = await run(generatedCheckCommand, args(root, []));
      expect(code).toBe(ExitCode.UsageError);
      expect(out).toContain('overlaps `provenanceHeader.mustMatch`');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('an uncompilable marker regex is refused at config load', async () => {
    const root = markerFixture('HAND(');
    try {
      const { code, out } = await run(generatedCheckCommand, args(root, []));
      expect(code).toBe(ExitCode.UsageError);
      expect(out).toContain('invalid regular expression');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('the marker is PER-FILE — an unmarked sibling is never covered by it', async () => {
    const root = markerFixture('HAND-AUTHORED, NOT GENERATED');
    try {
      writeFileSync(join(root, 'src/generated/D.ts'), 'export const D = 4;\n');
      const { out } = await run(generatedExplainCommand, args(root, [], { id: 'views' }));
      expect(out).toContain('[missing-header] src/generated/D.ts');
      expect(out).toContain('hand-maintained    1 file(s)');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

/** A repo whose only rule is warning-severity and does have a finding. */
function warningFixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'shrk-r69s-'));
  mkdirSync(join(root, 'sharkcraft'), { recursive: true });
  mkdirSync(join(root, 'src'), { recursive: true });
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'fx', version: '0.0.0' }));
  writeFileSync(join(root, 'src', 'a.ts'), "export const S = inject('svc');\n");
  writeFileSync(
    join(root, 'sharkcraft', 'sharkcraft.config.ts'),
    `export default {
  registrationGraph: [{
    name: 'di',
    declared: { files: ['src/*.ts'], extract: 'call-args', anchor: 'inject' },
    provided: { files: ['src/*.ts'], extract: 'call-args', anchor: 'provide' },
    consumed: { files: ['src/*.ts'], extract: 'call-args', anchor: 'inject' },
  }],
};
`,
  );
  return root;
}

describe('gates check --strict — the zero-warning CI switch', () => {
  test('by default a warning-severity finding reports without blocking', async () => {
    const root = warningFixture();
    try {
      const { code } = await run(gatesCheckCommand, args(root, []));
      expect(code).toBe(ExitCode.VerifiedPass);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('--strict promotes it to a failure, and says so', async () => {
    const root = warningFixture();
    try {
      const { code, out } = await run(gatesCheckCommand, args(root, [], { strict: true }));
      expect(code).toBe(ExitCode.Failure);
      expect(out).toContain('--strict promoted them to failures');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('--strict is inert when nothing reported findings', async () => {
    const root = warningFixture();
    try {
      writeFileSync(join(root, 'src', 'a.ts'), "provide('svc', 1);\nexport const S = inject('svc');\n");
      const { code } = await run(gatesCheckCommand, args(root, [], { strict: true }));
      expect(code).toBe(ExitCode.VerifiedPass);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('coverage read memo — a file change between runs is always seen', () => {
  test('two coverage runs across an edit report the NEW ids, never the cached ones', async () => {
    // The spec flagged this as unverified: a stale cache that missed a file
    // change would be a silent-green regression. This asserts at the VERDICT
    // level, not the byte level — the memo is scoped to one call, so a second
    // call must re-read the tree.
    const root = mkdtempSync(join(tmpdir(), 'shrk-r69c-'));
    try {
      mkdirSync(join(root, 'sharkcraft'), { recursive: true });
      mkdirSync(join(root, 'src'), { recursive: true });
      writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'fx', version: '0.0.0' }));
      writeFileSync(join(root, 'src', 'h.ts'), 'export const A_HANDLER = 1;\n');
      writeFileSync(
        join(root, 'sharkcraft', 'sharkcraft.config.ts'),
        `export default {
  registries: [{
    name: 'handlers',
    source: { files: ['src/*.ts'], extract: 'export-names', match: '_HANDLER$' },
  }],
};
`,
      );
      const first = await run(gatesCoverageCommand, args(root, []));
      expect(first.out).toContain('A_HANDLER');
      expect(first.out).toContain('1 ids');

      // Add a second handler between runs.
      writeFileSync(join(root, 'src', 'h.ts'), 'export const A_HANDLER = 1;\nexport const B_HANDLER = 2;\n');
      const second = await run(gatesCoverageCommand, args(root, []));
      expect(second.out).toContain('B_HANDLER');
      expect(second.out).toContain('2 ids');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
