import type { IPreset, IPresetIncludes } from '../model/preset.ts';

export interface ISynthesizedFile {
  /** Path relative to sharkcraft/. */
  path: string;
  content: string;
  /** Why this file was produced. */
  kind:
    | 'config'
    | 'knowledge'
    | 'rules'
    | 'paths'
    | 'templates'
    | 'pipelines'
    | 'docs'
    | 'tasks'
    | 'import-draft'
    | 'literal';
}

// Self-contained preambles for each emitted file kind. Generated files
// must work in a brand-new downstream repo where no `@shrkcrft/*`
// packages are installed. The loaders (knowledge / templates / pipelines)
// are shape-agnostic — they accept any object with the required string
// fields — so we just need helpers + enum-like constants the snippets
// reference. See `packages/knowledge/src/load/typescript-knowledge-loader.ts`
// for the loader contract.

const KNOWLEDGE_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
const KnowledgePriority = {
  Critical: 'critical',
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;

const KnowledgeType = {
  Rule: 'rule',
  Path: 'path',
  Template: 'template',
  Architecture: 'architecture',
  Technical: 'technical',
  Business: 'business',
  Command: 'command',
  Environment: 'environment',
  Dependency: 'dependency',
  Feature: 'feature',
  Task: 'task',
  Warning: 'warning',
  Decision: 'decision',
  Convention: 'convention',
  Workflow: 'workflow',
  Testing: 'testing',
  Security: 'security',
  Deployment: 'deployment',
  Integration: 'integration',
  Custom: 'custom',
} as const;

function defineKnowledgeEntry<T>(entry: T): T {
  return entry;
}
`;

const TEMPLATE_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
function defineTemplate<T>(template: T): T {
  return template;
}

function kebab(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .toLowerCase();
}
`;

const PIPELINE_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
function definePipeline<T>(pipeline: T): T {
  return pipeline;
}
`;

function recordToMap(
  v: ReadonlyMap<string, string> | Readonly<Record<string, string>> | undefined,
): ReadonlyMap<string, string> {
  if (!v) return new Map();
  if (v instanceof Map) return v;
  return new Map(Object.entries(v));
}

function listBlock(items: readonly string[] | undefined, indent = '  '): string {
  if (!items || items.length === 0) return '';
  return items.map((expr) => indent + expr.replace(/\n/g, `\n${indent}`)).join(',\n') + ',\n';
}

function knowledgeFile(items: readonly string[] | undefined): string {
  return (
    KNOWLEDGE_HELPERS +
    '\nconst knowledge = [\n' +
    listBlock(items) +
    '];\n\n' +
    'export default knowledge;\n'
  );
}

function rulesFile(items: readonly string[] | undefined): string {
  return (
    KNOWLEDGE_HELPERS +
    '\nconst rules = [\n' +
    listBlock(items) +
    '];\n\n' +
    'export default rules;\n'
  );
}

function pathsFile(items: readonly string[] | undefined): string {
  return (
    KNOWLEDGE_HELPERS +
    '\nconst paths = [\n' +
    listBlock(items) +
    '];\n\n' +
    'export default paths;\n'
  );
}

function templatesFile(items: readonly string[] | undefined): string {
  return (
    TEMPLATE_HELPERS +
    '\nconst templates = [\n' +
    listBlock(items) +
    '];\n\n' +
    'export default templates;\n'
  );
}

function pipelinesFile(items: readonly string[] | undefined): string {
  return (
    PIPELINE_HELPERS +
    '\nconst pipelines = [\n' +
    listBlock(items) +
    '];\n\n' +
    'export default pipelines;\n'
  );
}

function configFile(preset: IPreset): string {
  // Generic config that points at the standard knowledge/rules/paths/etc.
  // files. Consumers can tailor it later. Plain default-exported object —
  // the config loader (packages/config/src/config-loader.ts) validates the
  // shape via zod and accepts an object literal as well as a
  // `defineSharkCraftConfig()`-wrapped value, so the generated file does
  // not need to import anything from `@shrkcrft/*`.
  const filesByKind = inferFiles(preset);
  const knowledgeFiles = filesByKind.has('knowledge.ts') ? ['knowledge.ts'] : [];
  const ruleFiles = filesByKind.has('rules.ts') ? ['rules.ts'] : [];
  const pathFiles = filesByKind.has('paths.ts') ? ['paths.ts'] : [];
  const templateFiles = filesByKind.has('templates.ts') ? ['templates.ts'] : [];
  const pipelineFiles = filesByKind.has('pipelines.ts') ? ['pipelines.ts'] : [];
  const docsList = [...filesByKind.keys()].filter((p) => p.startsWith('docs/'));
  // When the preset declares a `surfaceProfile`, emit a `surface.profile`
  // block so the project starts with the right visible slice without
  // needing a separate `shrk surface` step.
  const surfaceBlock = preset.surfaceProfile
    ? `  surface: { profile: ${JSON.stringify(preset.surfaceProfile)} },\n`
    : '';
  return (
    `// Generated by \`shrk presets apply ${preset.id}\`.\n` +
    '// Edit freely. SharkCraft does not regenerate this file.\n' +
    '// Plain default export — no @shrkcrft/* import required.\n\n' +
    'const config = {\n' +
    `  projectName: 'shrk-project',\n` +
    `  description: ${JSON.stringify(preset.description)},\n` +
    `  knowledgeFiles: ${JSON.stringify(knowledgeFiles)},\n` +
    `  ruleFiles: ${JSON.stringify(ruleFiles)},\n` +
    `  pathFiles: ${JSON.stringify(pathFiles)},\n` +
    `  templateFiles: ${JSON.stringify(templateFiles)},\n` +
    `  pipelineFiles: ${JSON.stringify(pipelineFiles)},\n` +
    `  docsFiles: ${JSON.stringify(docsList)},\n` +
    `  defaultMaxTokens: 3500,\n` +
    surfaceBlock +
    '};\n\n' +
    'export default config;\n'
  );
}

function inferFiles(preset: IPreset): Map<string, string> {
  const files = new Map<string, string>();
  const inc = preset.includes;
  if (inc.knowledge && inc.knowledge.length > 0) {
    files.set('knowledge.ts', knowledgeFile(inc.knowledge));
  }
  if (inc.rules && inc.rules.length > 0) {
    files.set('rules.ts', rulesFile(inc.rules));
  }
  if (inc.paths && inc.paths.length > 0) {
    files.set('paths.ts', pathsFile(inc.paths));
  }
  if (inc.templates && inc.templates.length > 0) {
    files.set('templates.ts', templatesFile(inc.templates));
  }
  if (inc.pipelines && inc.pipelines.length > 0) {
    files.set('pipelines.ts', pipelinesFile(inc.pipelines));
  }
  const docs = recordToMap(inc.docs);
  for (const [name, content] of docs) {
    files.set(`docs/${name}`, content);
  }
  const tasks = recordToMap(inc.tasks);
  for (const [name, content] of tasks) {
    files.set(`tasks/${name}`, content);
  }
  return files;
}

/**
 * Pure synthesizer: return the list of files this preset would create under
 * the target's sharkcraft/ folder. Does not touch disk.
 */
export function synthesizePresetFiles(preset: IPreset): ISynthesizedFile[] {
  return synthesizeFromIncludes(preset, preset.includes, preset.filesToCreate ?? []);
}

/**
 * Synthesize files from a flattened {@link IResolvedPreset}. Uses the merged
 * `includes` from composition rather than the root preset's local includes.
 */
export function synthesizeResolvedPresetFiles(resolved: {
  preset: IPreset;
  includes: IPresetIncludes;
  filesToCreate: readonly { path: string; content: string }[];
}): ISynthesizedFile[] {
  return synthesizeFromIncludes(resolved.preset, resolved.includes, resolved.filesToCreate);
}

function synthesizeFromIncludes(
  preset: IPreset,
  includes: IPresetIncludes,
  filesToCreate: readonly { path: string; content: string }[],
): ISynthesizedFile[] {
  const out: ISynthesizedFile[] = [];
  out.push({ path: 'sharkcraft.config.ts', content: configFile({ ...preset, includes }), kind: 'config' });
  const files = inferFilesFromIncludes(includes);
  for (const [path, content] of files) {
    const kind: ISynthesizedFile['kind'] = path.endsWith('.ts')
      ? (path.replace('.ts', '') as ISynthesizedFile['kind'])
      : path.startsWith('docs/')
        ? 'docs'
        : path.startsWith('tasks/')
          ? 'tasks'
          : 'literal';
    out.push({ path, content, kind });
  }
  for (const f of filesToCreate) {
    out.push({ path: f.path, content: f.content, kind: 'literal' });
  }
  return out;
}

function inferFilesFromIncludes(inc: IPresetIncludes): Map<string, string> {
  const files = new Map<string, string>();
  if (inc.knowledge && inc.knowledge.length > 0) {
    files.set('knowledge.ts', knowledgeFile(inc.knowledge));
  }
  if (inc.rules && inc.rules.length > 0) {
    files.set('rules.ts', rulesFile(inc.rules));
  }
  if (inc.paths && inc.paths.length > 0) {
    files.set('paths.ts', pathsFile(inc.paths));
  }
  if (inc.templates && inc.templates.length > 0) {
    files.set('templates.ts', templatesFile(inc.templates));
  }
  if (inc.pipelines && inc.pipelines.length > 0) {
    files.set('pipelines.ts', pipelinesFile(inc.pipelines));
  }
  const docs = recordToMap(inc.docs);
  for (const [name, content] of docs) {
    files.set(`docs/${name}`, content);
  }
  const tasks = recordToMap(inc.tasks);
  for (const [name, content] of tasks) {
    files.set(`tasks/${name}`, content);
  }
  return files;
}
