import type { IImportedEntry } from '../model/imported-entry.ts';

/**
 * Render imported entries as a TypeScript module that defines a knowledge
 * base. The output is a self-contained, deterministic source file callers can
 * write into their `sharkcraft/` folder.
 *
 * Emitted files are intentionally free of `@shrkcrft/*` imports — the
 * knowledge loader is shape-agnostic, so the generated file declares its
 * own helpers + enum-like constants. This lets `shrk import` produce a
 * scaffolding file that works in a brand-new downstream repo where no
 * SharkCraft packages are installed beyond the CLI.
 *
 * The emitter avoids exotic escaping: it serializes each entry through
 * JSON.stringify with re-indentation and a final `as const` cast.
 */
export interface IEmitOptions {
  /** Header comment explaining where the file came from. */
  sourceLabel: string;
  /** Variable name to export (default: importedKnowledge). */
  exportName?: string;
}

const LOCAL_HELPERS = `// Local helpers — keep this file self-contained (no @shrkcrft/* imports).
const KnowledgePriority = {
  Critical: 'critical',
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;

const KnowledgeType = {
  Rule: 'rule',
  Path: 'path',
  Template: 'template',
  Architecture: 'architecture',
  Technical: 'technical',
  Business: 'business',
  Command: 'command',
  Environment: 'environment',
  Dependency: 'dependency',
  Feature: 'feature',
  Task: 'task',
  Warning: 'warning',
  Decision: 'decision',
  Convention: 'convention',
  Workflow: 'workflow',
  Testing: 'testing',
  Security: 'security',
  Deployment: 'deployment',
  Integration: 'integration',
  Custom: 'custom',
} as const;

function defineKnowledgeEntry<T>(entry: T): T {
  return entry;
}
`;

export function emitKnowledgeTs(entries: readonly IImportedEntry[], opts: IEmitOptions): string {
  const exportName = opts.exportName ?? 'importedKnowledge';
  const items = entries.map(serializeEntry).join(',\n');
  return [
    '// Auto-generated by `shrk import`.',
    `// Source: ${opts.sourceLabel}`,
    '// Review every entry — the importer is best-effort and types/priorities are inferred.',
    '',
    LOCAL_HELPERS,
    `export const ${exportName} = [`,
    items,
    '];',
    '',
  ].join('\n');
}

function escapeBackticks(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function serializeEntry(entry: IImportedEntry): string {
  const lines: string[] = [];
  lines.push('  defineKnowledgeEntry({');
  lines.push(`    id: ${JSON.stringify(entry.id)},`);
  lines.push(`    title: ${JSON.stringify(entry.title)},`);
  lines.push(`    type: KnowledgeType.${capitalize(entry.type)},`);
  lines.push(`    priority: KnowledgePriority.${capitalize(entry.priority)},`);
  if (entry.tags.length > 0) {
    lines.push(`    tags: ${JSON.stringify(entry.tags)},`);
  }
  if (entry.section) {
    lines.push(`    // section: ${JSON.stringify(entry.section)}`);
  }
  lines.push('    content: `' + escapeBackticks(entry.content) + '`,');
  lines.push('  })');
  return lines.join('\n');
}

function capitalize(s: string): string {
  // KnowledgeType / KnowledgePriority members are PascalCase enum members but
  // string values are kebab-or-lower; map known values explicitly.
  const map: Record<string, string> = {
    rule: 'Rule',
    path: 'Path',
    template: 'Template',
    architecture: 'Architecture',
    technical: 'Technical',
    business: 'Business',
    command: 'Command',
    environment: 'Environment',
    dependency: 'Dependency',
    feature: 'Feature',
    task: 'Task',
    warning: 'Warning',
    decision: 'Decision',
    convention: 'Convention',
    workflow: 'Workflow',
    testing: 'Testing',
    security: 'Security',
    deployment: 'Deployment',
    integration: 'Integration',
    custom: 'Custom',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  };
  return map[s] ?? s.charAt(0).toUpperCase() + s.slice(1);
}
